killbill/killbill

bin/db-helper
Sometimes user may use MySQL on other hosts, so that we should allow user to specify host for db-helper.
I added a new parameter "-H" for this. Actually, I prefer "-h", but it is already use for "help" action.
=> Add -H support for db-helper

bin/db-helper
I am introducing several enhancements for db-helper script:
1. Use `getopt` to parse parameters as it's more powerful
2. Add `--port` parameter
3. Add `--driver` parameter for PostgreSQL support
4. Correct `clean` action
=> Add PostgreSQL support to db-helper

invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java, invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatterFactory.java, invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceItemFormatter.java, invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java
this fixed #118: Invoice formatter displays now correct currency symbol
=> Correct currency symbol for different Locale and Invoice Currency

profiles/killbill/src/main/java/org/killbill/billing/server/security/TenantFilter.java
httpServletRequest.getPathInfo() returns now the correct path and does not include the server path where it is deployed.
=> #221 : Allow deployments as non-root resources.

jaxrs/pom.xml, jaxrs/src/main/java/org/killbill/billing/jaxrs/json/ComboPaymentTransactionJson.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/BundleResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CustomFieldResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/ExportResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/OverdueResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentGatewayResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentMethodResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginInfoResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SecurityResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TagDefinitionResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TagResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TenantResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
Replaces the `@Timed` annotations on jaxrs resources.
Solves #385 
Note: This PR adds the jersey-core jar as a dependency of killbill/jaxrs (see https://github.com/killbill/killbill/commit/c2eac6c4739db5b4e1b52942495105f5dd253913).
It's a transitive dependency that was removed when metrics-jersey was removed, but it's actually being directly used in the `org.killbill.billing.jaxrs.resources.PluginResource` class.
=> Timed resource metrics

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java, payment/src/main/java/org/killbill/billing/payment/provider/ExternalPaymentProviderPlugin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccount.java
Haven't created any test so far. Feedback welcome which test actually would make sense here as the effect of this method call highly depends on the plugin that is responsible for the payment methods. And the endpoint doesn't do anything else than calling the service method.
=> Create endpoint for refreshing of paymentmethods

profiles/killbill/src/main/java/org/killbill/billing/server/filters/ResponseCorsFilter.java
Add Access-Control-Expose-Headers to fix "Refused to get unsafe header" error when calling API from web browser via CORS
=> Add Access-Control-Expose-Headers to ResponseCorsFilter

jaxrs/src/main/java/org/killbill/billing/jaxrs/mappers/ExceptionMapperBase.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/mappers/PaymentApiExceptionMapper.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/ControlPluginRunner.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/PaymentControlApiAbortException.java, payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestRetryablePayment.java, payment/src/test/java/org/killbill/billing/payment/provider/MockPaymentControlProviderPlugin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java
Make sure an exception is thrown when a control plugin aborts a payment, and that the exception is correctly mapped to an HTTP response code*
\*Right now, the error is being mapped to [422 Unprocessable Entity](http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity).
=> Handle Control Plugin's Abort Payment instruction

profiles/killbill/pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/KillbillClient.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentGateway.java
Update code to use new methods and error handling.
Right now, this uses a work-around for referencing the latest version of KB's java client.
Once https://github.com/killbill/killbill-client-java/pull/36 is merged, and the oss parent module is updated, the pom.xml change in the PR can be removed.
=> Update KB Client in Profiles Module

payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java, payment/src/main/java/org/killbill/billing/payment/bus/PaymentBusEventHandler.java, payment/src/main/java/org/killbill/billing/payment/core/PluginControlPaymentProcessor.java, payment/src/main/java/org/killbill/billing/payment/logging/PaymentLoggingHelper.java
Add exception information to log entries generated by `DefaultPaymentApi`.
Example of new log entries:
```
2016-11-01T01:36:26.859+0000 [main] INFO org.killbill.billing.payment.api.DefaultPaymentApi -
EXITING PaymentApi: transactionType='CAPTURE', accountId='0682b47d-5777-4ae7-a82a-c000fd27b24c',
error='PAYMENT_INVALID_OPERATION', exception='Invalid payment transition CAPTURE from state UNKNOWN'
2016-11-01T01:36:29.304+0000 [main] INFO org.killbill.billing.payment.api.DefaultPaymentApi -
EXITING PaymentApi: transactionType='CHARGEBACK', accountId='559868ba-9b27-471c-aa80-e699416d0a6d',
error='PAYMENT_NO_SUCH_SUCCESS_PAYMENT', exception='Payment 7ab21fd1-c5f3-4f4a-be36-340952226d10 did not succeed'
2016-11-01T01:36:30.231+0000 [main] INFO org.killbill.billing.payment.api.DefaultPaymentApi …
```
=> Log exceptions in DefaultPaymentApi

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/BundleResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
Support AuditLevel when retrieving bundles and subscriptions using REST API.  I am building out a custom bundle/subscription view and needed the audit data - thought it might be useful to others as well 😀
=> Support AuditLevel when retrieving bundles and subscriptions

account/src/main/resources/org/killbill/billing/account/ddl.sql, beatrix/src/main/resources/org/killbill/billing/beatrix/ddl.sql, catalog/src/main/resources/org/killbill/billing/catalog/ddl.sql, entitlement/src/main/resources/org/killbill/billing/entitlement/ddl.sql, invoice/src/main/resources/org/killbill/billing/invoice/ddl.sql, payment/src/main/resources/org/killbill/billing/payment/ddl.sql, subscription/src/main/resources/org/killbill/billing/subscription/ddl.sql, tenant/src/main/resources/org/killbill/billing/tenant/ddl.sql, usage/src/main/resources/org/killbill/billing/usage/ddl.sql, util/src/main/resources/org/killbill/billing/util/ddl.sql, util/src/test/resources/org/killbill/billing/util/ddl_test.sql
Issue #652 - storage_engine is deprecated in mysql 5.7.5+, replacing with default_storage_engine.  I tested this on a few different mysql versions, but would appreciate it if someone else could test as well on their versions.  Is there documentation anywhere about what specific db versions killbill supports?  I will open separate pull request for killbill-platform.  😸
=> Issue #652 - storage_engine is deprecated in mysql 5.7.5+

profiles/killbill/src/main/java/org/killbill/billing/server/filters/ResponseCorsFilter.java
Would like to be able to use a session cookie for CORS requests to the KillBill API instead of including the `Authorization` header w/ username and password on every request.  Setting the `Access-Control-Allow-Credentials` header allows the use of cookies, but prohibits using `*` for  `Access-Control-Allow-Origin`, so I'm just echoing back the request origin.  I know this isn't a perfect solution.. ideally we could check against a configurable list of whitelisted origins.  Any thoughts? :smiley:
=> Allow cookies for CORS requests

profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/PatternObfuscator.java, profiles/killbill/src/test/java/org/killbill/billing/server/log/obfuscators/TestPatternObfuscator.java
Make sure we match `JSON` patterns with leading spaces before colons.
Also, improves obfuscation a bit for cases where value to be obfuscated appears before a closing brace (i.e. `{"cvv" : 123}`). Before, the closing brace would be replaced with a `*`.
=> Improve JSON pattern matching/substitution

jaxrs/src/main/java/org/killbill/billing/jaxrs/json/InvoiceJson.java
As discussed on the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/killbilling-users/tqLBV0xE3OY/bK2GoupXAgAJ), this fixes the incorrect mapping of one JSON attribute.
=> Fix json key mapping

catalog/src/main/java/org/killbill/billing/catalog/DefaultUnit.java, catalog/src/main/java/org/killbill/billing/catalog/VersionedCatalog.java, catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/json/CatalogJson.java
Discussed w/ @sruthipendyala - we thought it is better to include one list of all the units w/ prettyName instead of including prettyName on every single tier block - this also allows the API to be backwards compatible.  Reverted the commit that removed unit and added name and prettyName to TierBlockJson, added back prettyName functionality to DefaultUnit, added units to CatalogJson.  🌴
=> Add units list to CatalogJson

invoice/src/main/java/org/killbill/billing/invoice/model/ExternalChargeInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemFactory.java
Updated ExternalChargeInvoiceItem to extend InvoiceItemCatalogBase.  Invoice plugin api allows you to add planName, linkedInvoiceId, etc to external charge and they will be stored in the db, but not retrieved via API or populated in analytics table - this fixes the issue.  External charges w/o the additional fields will continue to work the same.
=> Update ExternalChargeInvoiceItem to extend InvoiceItemCatalogBase

entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementContext.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TestResource.java, overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueAsyncBusPoster.java, overdue/src/test/java/org/killbill/billing/overdue/notification/TestDefaultOverdueCheckPoster.java, overdue/src/test/java/org/killbill/billing/overdue/notification/TestOverdueCheckNotifier.java, payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java, payment/src/main/java/org/killbill/billing/payment/core/sm/payments/ChargebackInitiated.java, payment/src/test/java/org/killbill/billing/payment/TestJanitor.java, payment/src/test/java/org/killbill/billing/payment/core/janitor/TestIncompletePaymentTransactionTaskWithDB.java, util/src/main/java/org/killbill/billing/util/cache/EhCacheBasedCacheController.java, util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java
Syntax tweaks to resolve _The method X of type Y is not generic; it cannot be parameterized with arguments Z_ style errors reported by ECJ during compilation (in Eclipse); see the mailing list for the [initial discussion](https://groups.google.com/d/msg/killbilling-users/LzgXLH16k5c/EtBjEP96AgAJ).
I have verified all modules build cleanly via Maven and all tests pass.
=> Syntax tweaks to resolve errors reported by ECJ

payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
When refreshing payment methods, set payment method external key if provided.
=> Set external key when refreshing payment methods

util/src/main/resources/org/killbill/billing/util/ddl-postgresql.sql
In MySQL the record_id columns are created as type `serial` which is a 64-bit integer, but `serial` in Postgres is a 32-bit integer (the `bigserial` type is 64-bit). Add an event trigger function that alters `serial` columns to the `bigint` type after a `CREATE TABLE` DDL event.
=> Make record_id columns the bigint type in Postgres

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
Fix issue where invoice id does not show in swagger ui for posting invoice payments.  This causes 404 error when using this endpoint via Swagger UI.  Made use of path param consistent w/ other invoice endpoints and removed an unnecessary if/else.  Let me know if I need to make any changes! 🤓
=> Invoice Payment Swagger Fix

payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
Fix for "org.killbill.billing.payment.api.PaymentApiException: Internal payment error : Payment method xxx does not exist" when a default payment method is removed and a different payment method is selected as default during a payment method refresh.  Payment method has already been deleted by the time we get to this point, so we need to include deleted payment methods when retrieving old payment method.
=> Payment Method Refresh Fix

payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
Fix for issue where account paymentMethodId would not be updated when a payment method refresh removed the default payment method and did not specify a new default payment method.  Removing unnecessary null check since we are already checking if the current (old) default payment method is from the same plugin before the modifying the account's payment method id (so we should never overwrite an account's payment method id if that payment method is from a different plugin.)
=> Payment Method Refresh / Account Payment Method fix

invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceItemGenerator.java
This fixes https://github.com/killbill/killbill/issues/851.
You can re-enable this logging by adding the following to your logback.xml:
```
<logger name="org.killbill.billing.invoice.generator" level="DEBUG"/>
```
=> invoice: reduce log level of InvoiceItemGeneratorLogger

util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoTransactionalJdbiWrapper.java
This saves 3 roundtrips per transaction.
=> util: set the default transaction isolation level at the pool level

util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoTransactionalJdbiWrapper.java, util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java
This is useful for debugging issues at runtime (e.g. performance).
```
16:37:06.151 [http-worker-78] INFO  c.s.j.a.c.filter.LoggingFilter - 3 * Server in-bound request
3 > POST http://127.0.0.1:8080/1.0/kb/accounts
3 > X-Killbill-ApiKey: e3cea2a3-0aa8-41fd-a438-6770425f872d
3 > Authorization: Basic dGVzdGVyOnRlc3Rlcg==
3 > X-Killbill-ApiSecret: df23bdc6-0429-4169-821f-cbbf4db425da
3 > Accept: application/json
3 > Connection: keep-alive
3 > User-Agent: KillBill-JavaClient/1.0
3 > X-Killbill-Reason: testing
3 > Host: 127.0.0.1:8080
3 > X-Killbill-CreatedBy: Toto
3 > X-Killbill-Comment: no comment
3 > Content-Length: 664
3 > Content-Type: application/json; charset=UTF-8
3 > 
16:37:06.163 [http-worker-78] DEBUG  o.k.b.u.g.KillbillApiAopModule - Entering API call public void …
```
=> util: add useful DEBUG-level log entries

jaxrs/src/main/java/org/killbill/billing/jaxrs/util/JaxrsUriBuilder.java
When `useForwardHeaders` is enabled, use `request.getServerName()` instead of `uriInfo` to get the hostname.  In cases where multiple dns names point at a single killbill instance, the hostname used to access the api will be the one returned in the location header (when `jaxrsLocationHost` is not specified).  Let me know if you see any issues!  :bowtie:
=> Use request.getSeverName() when useForwardHeaders is enabled

util/src/main/java/org/killbill/billing/util/tag/dao/DefaultTagDefinitionDao.java
#822 - Fix for `NullPointerException` when tag definition does not exist.
=> Fix for #822

entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java, subscription/src/test/java/org/killbill/billing/subscription/SubscriptionTestSuiteWithEmbeddedDB.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/TestSubscriptionDao.java, util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoTransactionalJdbiWrapper.java, util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java, util/src/test/java/org/killbill/billing/GuicyKillbillTestSuiteWithEmbeddedDB.java
If an API call uses the RW instance and then fetches data from the RO instance, state might be inconsistent due to replication delays between master and slave(s).
To work-around this, add a thread local dirty flag: if data is changed, any further call will use the RW instance.
=> util: introduce thread-local dirty DB flag

invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
Fix for issue where invoice items returned by plugins are not added to the invoice.  Short circuit or prevented `updateOriginalInvoiceWithPluginInvoiceItems` from being called after the 1st invoice plugin.
=> Fix for multiple invoice plugin issue

pom.xml, util/pom.xml, util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java
Unless plugins explicitly request it, redirect all plugin calls to the RW instance to work around replication delays.
See https://github.com/killbill/killbill-platform/pull/30 and https://github.com/killbill/killbill-analytics-plugin/pull/80.
=> util: don't always use RO DB by default

profiles/killbill/src/test/java/org/killbill/billing/server/security/TestKillbillJdbcTenantRealm.java, usage/src/main/java/org/killbill/billing/usage/dao/DefaultRolledUpUsageDao.java, util/src/main/java/org/killbill/billing/util/audit/dao/DefaultAuditDao.java, util/src/main/java/org/killbill/billing/util/broadcast/dao/DefaultBroadcastDao.java, util/src/main/java/org/killbill/billing/util/cache/AuditLogCacheLoader.java, util/src/main/java/org/killbill/billing/util/dao/DefaultNonEntityDao.java, util/src/main/java/org/killbill/billing/util/entity/dao/DBRouter.java, util/src/main/java/org/killbill/billing/util/entity/dao/DBRouterUntyped.java, util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoTransactionalJdbiWrapper.java, util/src/main/java/org/killbill/billing/util/nodes/dao/DefaultNodeInfoDao.java, util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java, util/src/main/java/org/killbill/billing/util/validation/dao/DatabaseSchemaDao.java, util/src/test/java/org/killbill/billing/util/validation/TestValidationManager.java
Encapsulate the logic to route between RO and RW DB instance. That way, we always honor the `perThreadDirtyDBFlag`.
=> util: introduce DBRouter

invoice/src/main/java/org/killbill/billing/invoice/usage/details/UsageConsumableInArrearTierUnitAggregate.java, invoice/src/main/java/org/killbill/billing/invoice/usage/details/UsageInArrearTierUnitDetail.java
Ignore unknown properties when deserializing invoice item item details - this allows plugins to add their own "stuff" to item details in addition to the built-in tier/unit/quantity.  Let me know if there are any issues! 🤓
=> Ignore unknown properties when deserializing invoice item item details

beatrix/src/test/java/org/killbill/billing/beatrix/integration/BeatrixIntegrationModule.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/db/TestDBRouter.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/db/TestDBRouterAPI.java, payment/src/test/java/org/killbill/billing/payment/TestJanitor.java, payment/src/test/java/org/killbill/billing/payment/provider/MockPaymentProviderPlugin.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/JaxRSAopModule.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillbillServerModule.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestDBRouterResources.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestJaxrsBase.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/resources/TestDBRouterResource.java, profiles/killpay/src/main/java/org/killbill/billing/server/modules/KillpayServerModule.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/TestSubscriptionDao.java, util/src/main/java/org/killbill/billing/util/entity/dao/DBRouterUntyped.java, util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java, util/src/test/java/org/killbill/billing/GuicyKillbillTestSuiteWithEmbeddedDB.java
RO DBI is now invoked only for JAX-RS `GET` endpoints and when plugins specifically ask for it.
=> util: always redirect bus events and notifications to RW DB instance

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPublicBus.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java, catalog/src/main/java/org/killbill/billing/catalog/VersionedCatalog.java, catalog/src/test/java/org/killbill/billing/catalog/MockCatalog.java, entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EventsStreamBuilder.java, entitlement/src/test/java/org/killbill/billing/entitlement/block/TestBlockingChecker.java, entitlement/src/test/java/org/killbill/billing/entitlement/engine/core/TestEntitlementUtils.java, junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java, junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBillingApi.java, pom.xml, subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionBaseCreateApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/timeline/DefaultSubscriptionBaseTimelineApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/engine/addon/AddonUtils.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/SubscriptionDao.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/model/SubscriptionModelDao.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiAddOn.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoMemory.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/TestSubscriptionDao.java, util/src/test/java/org/killbill/billing/api/TestApiListener.java
As discussed, I unfortunately pushed 2 additional commits by mistake on the main `work-for-release-0.19.x` branch:
* b9ecb8900db899ab6439cdffc5fc809446040b68: removal of legacy APIs and trivial cleanups
* 7365574f63933c3124d0b0cf3e9e45657f3996ad: refactoring of the create codepath, to make sure the right Catalog APIs are used in the right places, with the right dates (I fixed https://github.com/killbill/killbill/commit/7365574f63933c3124d0b0cf3e9e45657f3996ad#diff-1804fde088390c1b6e9719d17cd2f7b2L285 for instance)
This PR has just the latest commit to implement the new grandfathering APIs. The big change `SubscriptionBase` -> `DefaultSubscriptionBase` was to be able to access the `alignStartDate` when fetching alignments. I was also able to greatly simplify `AddonUtils` (number of calls …
=> catalog: implement new grandfathering APIs

invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemFactory.java, invoice/src/main/java/org/killbill/billing/invoice/model/TaxInvoiceItem.java
Populate item details for TaxInvoiceItem.  Currently plugins can save itemDetails for a TAX item, but the field will be null via API calls or additional plugin runs - this corrects the issue.
=> Populate item details for TaxInvoiceItem

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java, payment/src/main/java/org/killbill/billing/payment/api/DefaultInvoicePaymentApi.java, pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestChargeback.java
The chargeback APIs weren't plugged properly. This should fix the failing Ruby integration tests.
=> jaxrs: fix regression in InvoicePaymentResource

invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java
This PR comes out of [discussion on the mailing list](https://groups.google.com/d/msg/killbilling-users/of8TMBlzF7A/szSxkMUPCAAJ).
=> Fix for NPE if the only available usage is before the first transition date

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
Set String encoding to UTF-8 when returning response from plugin servlet.  Fixes issue where special character in response entity caused malformed json to be returned from the servlet endpoint.
=> Fix string encoding in PluginResource

catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
This was breaking the Kaui screen to add currency on an existing plan.
=> catalog: revisit simple plan validation

invoice/src/main/java/org/killbill/billing/invoice/model/TaxInvoiceItem.java
I'm currently working on a Tax Plugin. 
During development, I noticed something strange. The linkedItemId was always null on a tax-Item - even if the database item has a linkedItemId set. 
after some researched, I noticed that during the mapping from the Database invoice Dao to the actual TaxItem object, the linkedItemId information gets lost. 
Long story short -  I added the linkedItemId field to the super() call in TaxInvoiceItem
=> Fixes linkedItemId-mapping issue for TaxInvoiceItem

pom.xml, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillSessionStorageEvaluator.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillWebSubjectDAOProvider.java, util/src/main/java/org/killbill/billing/util/glue/EhcacheShiroManagerProvider.java, util/src/main/java/org/killbill/billing/util/glue/KillBillShiroModule.java, util/src/main/java/org/killbill/billing/util/glue/KillBillSubjectDAOProvider.java, util/src/main/java/org/killbill/billing/util/glue/RedisShiroManagerProvider.java, util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java, util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionSqlDao.java, util/src/main/resources/org/killbill/billing/util/security/shiro/dao/JDBCSessionSqlDao.sql.stg
1. Only create sessions via the /1.0/kb/security/permissions path
2. Make sure old sessions are purged from the database
3. Authenticate plugin requests if credentials are provided 
Regarding 1.: any other API call with an Authorization header won't create sessions anymore: this will prevent useless state to be created with our official API clients, which don't use the `JSESSIONID` mechanism, and leave the Kaui integration unchanged.
Custom implementations may need to be updated.
```
~ > curl -v \
-uadmin:password \
-H'X-Killbill-ApiKey: bob' \
-H'X-Killbill-ApiSecret: lazar' \
http://127.0.0.1:8080/1.0/kb/accounts/8313b0fd-99e2-4d35-bde3-035550f83293
...
< Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Mon, 22-Oct-2018 08:24:48 GMT
~ > curl -v \
-uadmin:password \ …
```
=> security: Shiro changes

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemFactory.java, invoice/src/main/java/org/killbill/billing/invoice/model/TaxInvoiceItem.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemDao.java
The `endDate` is a possible propertie for a tax-item, since the
following methode from killbill-base-plugin makes use of it:
`org.killbill.billing.plugin.api.invoice.PluginInvoiceItem#createTaxItem`
https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/api/invoice/PluginInvoiceItem.java#L58
This PR adds the mapping entry needed to map the endDate from the InvoiceItemDao back to the TaxItem item
=> Fixes issue with the endDate mapping for tax items

.idea/inspectionProfiles/Project_Default.xml, account/src/main/java/org/killbill/billing/account/api/DefaultAccount.java, account/src/main/java/org/killbill/billing/account/api/svcs/DefaultAccountInternalApi.java, account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountUserApi.java, account/src/main/java/org/killbill/billing/account/dao/AccountDao.java, account/src/main/java/org/killbill/billing/account/dao/AccountModelDao.java, account/src/main/java/org/killbill/billing/account/dao/DefaultAccountDao.java, account/src/test/java/org/killbill/billing/account/dao/MockAccountDao.java, account/src/test/java/org/killbill/billing/account/dao/TestAccountDao.java, api/src/main/java/org/killbill/billing/junction/BillingInternalApi.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithBCDUpdate.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/json/AccountJson.java, junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java
See https://github.com/killbill/killbill/issues/282.
This also fixes the build after the recent merge (test issue) and integrates your comment w.r.t. dry-run and account BCD.
=> Fix for 282

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoiceWithRepairLogic.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/ExistingInvoiceMetadata.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDao.java, invoice/src/test/java/org/killbill/billing/invoice/dao/MockInvoiceDao.java
Instead of fetching existing invoices and invoice items one by one in the `createInvoices` transaction (e.g. `AUTO_INVOICING_REUSE_DRAFT` use case), bulk retrieve all of them.
In the case of regular invoice runs, this will likely speed up things, because we already have the information (we save at least 2 queries per invoice run, linear with the number of invoice items being created). However, in the case of direct API calls (e.g. create adjustment) and HA (bus listener), this will likely slow things down (in most cases, we will retrieve more information than actually needed). Since these are infrequent codepaths, it's probably okay (we could optimize further depending on the codepath, but it would increase the DAO logic complexity).
@sbrossie FYI, this is orthogonal to the caching work …
=> invoice: reduce number of queries when creating invoices

jaxrs/src/main/java/org/killbill/billing/jaxrs/json/PaymentMethodJson.java, payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java, util/src/main/java/org/killbill/billing/util/PluginProperties.java, util/src/test/java/org/killbill/billing/util/TestPluginProperties.java
Fix for NPE when `paymentMethodProps.getProperties()` returns null.
When payment control plugins are in use and an `__EXTERNAL_PAYMENT__` payment method is added via `AccountApi::createPaymentMethod`, a NPE is thrown.  Added check to skip merge when payment method properties are null.
Full stacktrace:
```
java.lang.NullPointerException: null
at org.killbill.billing.util.PluginProperties.toMap(PluginProperties.java:41)
at org.killbill.billing.util.PluginProperties.merge(PluginProperties.java:34)
at org.killbill.billing.payment.core.PaymentMethodProcessor.addPaymentMethodWithControl(PaymentMethodProcessor.java:181)
at org.killbill.billing.payment.api.DefaultPaymentApi.addPaymentMethodWithPaymentControl(DefaultPaymentApi.java:995)
at …
```
=> Fix for NPE when `paymentMethodProps.getProperties()` returns null.

util/src/main/java/org/killbill/billing/util/export/dao/CSVExportOutputStream.java, util/src/test/java/org/killbill/billing/util/export/dao/TestCSVExportOutputStream.java
KPM relies on a couple of special characters to process the data.
=> util: escape special characters during export process

profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java
1. Increase HTTP client connect timeout from 5s to 15s
2. Make sure we always retry regardless of the exception
Bug 2. was actually caught during the code review, but we didn't follow-up on it 😞: https://github.com/killbill/killbill/pull/589#discussion_r72986513
=> server: improve push notifications errors handling

profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestSecurity.java, util/src/main/java/org/killbill/billing/util/glue/KillBillShiroModule.java, util/src/main/java/org/killbill/billing/util/glue/RealmsFromShiroIniProvider.java, util/src/main/java/org/killbill/billing/util/security/api/DefaultSecurityApi.java, util/src/test/java/org/killbill/billing/util/UtilTestSuiteWithEmbeddedDB.java, util/src/test/java/org/killbill/billing/util/glue/TestUtilModuleWithEmbeddedDB.java, util/src/test/java/org/killbill/billing/util/security/api/TestDefaultSecurityApi.java, util/src/test/java/org/killbill/billing/util/security/shiro/realm/TestKillBillJdbcRealm.java, util/src/test/resources/shiro.ini
Note the behavior change: wildcard permissions aren't expanded anymore. Built-in (`"account:*"`) and custom (`"acme:*"`) permissions will not be expanded in the API (as custom Realms don't necessarily
expose this information).
This fixes https://github.com/killbill/killbill/issues/1133.
=> security: return custom permissions from all Realms

entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java, subscription/src/test/java/org/killbill/billing/subscription/api/svcs/TestEffectiveDateForNewBCD.java
This fixes https://github.com/killbill/killbill/issues/1158.
=> subscription: ensure BCD event is after CREATE event

entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionBaseCreateApi.java
The ErrorCode `SUB_CREATE_INVALID_ENTITLEMENT_SPECIFIER` doesn't allow for an error message to be passed. Add some logging to help the user understand the issue.
=> entitlement: subscription: add logging around invalid specifiers

profiles/killbill/src/main/webapp/WEB-INF/web.xml
Set `async-supported` in all our filters so that things like SSE are supported out of the box.
/cc @laurentbh
=> server: support for Async

profiles/killbill/src/main/java/org/killbill/billing/server/filters/KillbillMDCInsertingServletFilter.java, util/src/main/java/org/killbill/billing/util/callcontext/InternalCallContextFactory.java
The `userToken` wasn't cleaned-up, so it was shared across requests, making production logs debugging quite confusing 😑
=> server: make sure to clear the userToken from the MDC context

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
In case a duplicate transaction external key was used, invoice would throw a NPE in the priorCall.
This fixes https://github.com/killbill/killbill/issues/1230.
=> invoice: fix NPE in DefaultInvoiceDao

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemBase.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java, payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java, payment/src/main/java/org/killbill/billing/payment/invoice/dao/InvoicePaymentControlDao.java, payment/src/main/java/org/killbill/billing/payment/invoice/dao/PluginAutoPayOffModelDao.java, payment/src/main/resources/org/killbill/billing/payment/ddl.sql, payment/src/main/resources/org/killbill/billing/payment/migration/V20191001160927__remove_invoice_payment_control_plugin_auto_pay_off_payment_method_id.sql, payment/src/test/java/org/killbill/billing/payment/invoice/dao/TestInvoicePaymentControlDao.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/KillbillClient.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestBundle.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestChargeback.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoicePayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceVoid.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestTag.java, util/src/main/java/org/killbill/billing/util/userrequest/CompletionUserRequestBase.java
This fixes https://github.com/killbill/killbill/issues/812, https://github.com/killbill/killbill/issues/1193 and https://github.com/killbill/killbill/issues/1211.
=> payment: perform AUTO_PAY_OFF check early when paying invoices

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
Make sure we support plugins paths including "plugins" (e.g. `/plugins/killbill-kpm/plugins`).
=> jaxrs: fix PluginResource implementation

util/src/main/java/org/killbill/billing/util/callcontext/InternalCallContextFactory.java
`tenantRecordId` should never be `null`: add some validation in case a plugin attempts to call the `TenantUserApi` on an invalid `tenantId` for instance.
=> util: ensure getTenantRecordIdUnsafe returns a non-null tenantRecordId

entitlement/src/test/java/org/killbill/billing/entitlement/glue/TestEntitlementModule.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillbillServerModule.java, profiles/killpay/src/main/java/org/killbill/billing/server/modules/KillpayServerModule.java, tenant/src/test/java/org/killbill/billing/tenant/glue/TestTenantModuleNoDB.java, util/src/main/java/org/killbill/billing/util/glue/KillBillShiroAopModule.java, util/src/main/java/org/killbill/billing/util/security/PermissionAnnotationHandler.java, util/src/main/java/org/killbill/billing/util/security/PermissionAnnotationMethodInterceptor.java, util/src/test/java/org/killbill/billing/util/glue/TestUtilModuleNoDB.java, util/src/test/java/org/killbill/billing/util/security/TestPermissionAnnotationMethodInterceptor.java
When `org.killbill.security.skipAuthForPlugins=true`, plugins calling Kill Bill APIs with a context where `CallOrigin.INTERNAL` and `UserType.ADMIN` will not need to be authenticated.
=> shiro: add mechanism to bypass authentication from plugins

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java
Handle the case of invoice payments with a NULL payment id (i.e. when the payment is aborted by a payment control plugin). These won't be returned by the API.
For testing, I had to add a new (undocumented) query parameter to the createInstantPayment API, in order to add an additional payment control plugin to the chain.
This fixes https://github.com/killbill/killbill/issues/1288.
=> jaxrs: fix NPE in getPaymentsForInvoice

beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestConsumableInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
* Revisit log line to make it clearer and easier to debug
* Adjust test to highlight system behavior
=> invoice: clarify behavior for skipping overlapping usage items

util/src/main/java/org/killbill/billing/util/config/definition/RedisCacheConfig.java, util/src/main/java/org/killbill/billing/util/glue/RedissonCacheClientProvider.java, util/src/test/java/org/killbill/billing/GuicyKillbillTestSuite.java
Our Redis deployment supports password connections only. Kindly your consideration on adding this feature.
=> Add support for Redis password connections

subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
This fix is to address the situation I find myself in, where I have many existing subscriptions and existing catalog versions, but only the most recent catalog version specifies an `effectiveDateForExistingSubscriptions` value. My expectation was that this would cause the plan to be applied to existing subscriptions starting on that date, but it was not. Upon investigation, I found a loop that stopped looking at catalog versions if no `effectiveDateForExistingSubscriptions` was specified. Thus it stopped looking too soon and never found the catalog version that _did_ have that date specified. After applying this fix, my invoices started picking up the most recent catalog prices, as expected.
=> Fix for plan changes that eventually specify an effectiveDateForExistingSubscriptions value

usage/src/main/java/org/killbill/billing/usage/api/BaseUserApi.java, usage/src/main/java/org/killbill/billing/usage/api/user/DefaultUsageUserApi.java
This is useful for usage plugins for instance.
=> usage: ensure TenantContext#getAccountId is always populated

invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java, invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
This is a workaround for https://github.com/killbill/killbill/issues/1312 until the API can be changed.
Note: this patch was originally submitted against the `emb-project` branch. Backporting the fix against master for it to be considered for the next release.
=> invoice: allow invoice plugins to modify plugin properties

invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java, invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceItemFormatter.java, payment/pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jetty/HttpServer.java, util/pom.xml
A few formatting tests have been disabled, as the behavior is JDK dependent:
* Type of space used has changed (related: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4510618)
* Default negative numbers representation has changed (related: https://bugs.openjdk.java.net/browse/JDK-8221245)
All tests pass locally on OpenJDK Runtime Environment (build 14.0.2+12-46). CI doesn't support 14 yet though.
=> Add support for jdk14

util/src/main/java/org/killbill/billing/util/config/definition/CatalogConfig.java
We had several `SpyCarBasic.xml`, so I removed the one in the killbill profile in 0.22.12 (we now only ship `SpyCarAdvanced.xml` without a namespace). The config wasn't changed before the release unfortunately. 
For now, I've updated the docs: https://github.com/killbill/killbill-docs/commit/1ed21a18c6493234a5719781f32d993c60adfd1c
=> util: change default catalog

catalog/pom.xml, catalog/src/main/java/org/killbill/billing/catalog/CatalogSafetyInitializer.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultBlock.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultCatalogService.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultPrice.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultTieredBlock.java, catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java, catalog/src/test/java/org/killbill/billing/catalog/MockCatalogService.java, catalog/src/test/java/org/killbill/billing/catalog/TestCatalogService.java, subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestDefaultSubscriptionTransferApi.java, util/src/main/java/org/killbill/billing/util/cache/KillBillCacheController.java, util/src/main/java/org/killbill/billing/util/config/definition/CatalogConfig.java
This PR focuses on several performance aspects:
1. Slowness of loading a large number of catalogs: one can now specify `org.killbill.catalog.loader.threads.pool.nb`to load catalogs in parallel
2. Memory usage:
* Ensure a single thread loads the catalog (synchronization)
* Reduce the amount of `Double` and `BigDecimal` objects created
Testing was done on my laptop with 74 catalogs (~800 MB). Load time was cut from 28s to 18s (with 5 threads).
=> Catalog performance

invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDatePoster.java, util/src/test/java/org/killbill/billing/DBTestingHelper.java
This also works around the new MySQL transient auth errors. They don't appear on CircleCI and they sometimes appear on GitHub actions (I had added a workaround already in the workflow file: https://github.com/killbill/killbill-oss-parent/blob/ec9515d6435f59afac4fdd394d216bcbe4a24bbc/.github/workflows/ci.yml#L154).
I debugged it - the MySQL server indeed sometimes returns a SqlState 28000. Not sure why 🤷 Reconnecting right away solves it.
=> Invoice performance fixes

util/src/main/resources/org/killbill/billing/util/ddl.sql, util/src/main/resources/org/killbill/billing/util/migration/V20200916171757__recreate_users_index_as_unique.sql
Without this, two requests can come in at the same time and result in duplicate users.
Discussed on mailing list [here](https://groups.google.com/g/killbilling-users/c/KBTGCF3_AI4).
=> Index on users.username should be unique

invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemCatalogBase.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemDao.java
This fixes https://github.com/killbill/killbill/issues/1370.
=> invoice: ignore sub-second precision when matching items

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogEffectiveDate.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithCatalogUpdate.java, beatrix/src/test/resources/catalogs/testCatalogEffectiveDate/WeaponsHireSmall-v1.xml, beatrix/src/test/resources/catalogs/testCatalogEffectiveDate/WeaponsHireSmall-v2.xml, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemCatalogBase.java
A mismatch of `catalogEffectiveDate` on disk will be ignored moving forward (e.g we won't trigger a repair).
This works around https://github.com/killbill/killbill/issues/1373: in junction, we don't have enough information to get the "sticky" catalog in case a subsequent catalog was uploaded in the past at t1 < t < t2, where t1 is the initial catalog effective
date and t2 the billing event effective date.
=> invoice: skip catalogEffectiveDate check during invoicing

profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillEmbeddedDBProvider.java
`killbill-platform-server` does ship `org/killbill/billing/server/ddl.sql` but we don't need to install it in Kill Bill.
=> server: remove server from list of DDL to install

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxrsResource.java, pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/KillbillClient.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccountTimeline.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestChargeback.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCredit.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestExternalRefund.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceItem.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoicePayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceVoid.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestOverdue.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestUsage.java
The new behavior for AccountResource#payAllInvoices was implemented in https://github.com/killbill/killbill/pull/1433/commits/74c4f3930fa9267e7c38d0de997e4f9879e6a142
Note: ci tests canceled until we release the new java client -- see https://github.com/killbill/killbill-client-java/pull/89
=> Update against latest java client + enhance AccountResource#payAllInvoices

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithDryRun.java, beatrix/src/test/resources/catalogs/testCatalogWithDryRun/WeaponsHireSmall-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithDryRun/WeaponsHireSmall-v2.xml, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/catalog/SubscriptionCatalog.java
Fix issue in dry-run to ensure we pick up the right catalog version when there is a pending catalog between NOW and the effective date of the dry-run action.
Also fix a TODO in that path in https://github.com/killbill/killbill/pull/1441/commits/0aaec584c926af5c52b3b7b0de8bc10d0d36ae41
=> Dry run with pricelist

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithDryRun.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInArrear.java, beatrix/src/test/resources/catalogs/testCatalogWithDryRun/WeaponsHireSmall-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithDryRun/WeaponsHireSmall-v2.xml, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/catalog/SubscriptionCatalog.java, usage/src/main/resources/org/killbill/billing/usage/dao/RolledUpUsageSqlDao.sql.stg
This fixes https://github.com/killbill/killbill/issues/1438.
Suggestions for the reviewer:
* Verify expectations in the new Beatrix tests in `TestUsageInArrear.java`. It's always the same scenario (yearly base subscription with usage-based add-on), the main differences are operations taken on the add-on subscription (various cancellation dates or cancel/uncancel).
* Notice how I had to change the `getRawUsageForAccount` query to match the expected behavior of a usage plugin (last day is inclusive).
* Let me know if you think of other regression scenarii to write?
=> invoice: take into account usage points at cancellation day

invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java
https://github.com/killbill/killbill/pull/1442/commits/ee68ef7b4efd3b9a58aae5b14723e87f581b4708 : Only commit worth looking at (unclear why there are so many since both branches `fix-for-usages-at-cancel-date` and `fix-for-usages-at-cancel-date2` are up to date with `master` 🤔
=> Add invoice unit tests for usage transitions + code refactoring

entitlement/src/main/java/org/killbill/billing/entitlement/dao/BlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/BlockingStateSqlDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EventsStreamBuilder.java, entitlement/src/main/resources/org/killbill/billing/entitlement/dao/BlockingStateSqlDao.sql.stg, entitlement/src/test/java/org/killbill/billing/entitlement/dao/MockBlockingStateDao.java, entitlement/src/test/java/org/killbill/billing/entitlement/dao/TestBlockingDao.java
Prior the fix, we would pull all blocking states on the account, but after the fix we pull the minimum we need,
which is whatever is set at the `ACCOUNT`, `SUBSCRIPTION_BUNDLE` and `SUBSCRIPTION` -- both base subscription and add-on if required -- level.
⚠️ This is by no means this end of the story, but I think this should take care of the following bottlenecks:
```
at org.killbill.billing.entitlement.dao.DefaultBlockingStateDao.getBlockingAllForAccountRecordId(DefaultBlockingStateDao.java:191)
at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForEntitlement(EventsStreamBuilder.java:313)
at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForEntitlement(EventsStreamBuilder.java:293)
at org.killbill.billing.entitlement.engine.core.EventsStreamBuil …
```
=> entitlement: Optimize path where we fetch an entitlement by id

entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java, junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BlockingCalculator.java, junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBlockingCalculator.java
Stacktraces from the load test:
```
catalina-exec-3" #107 daemon prio=5 os_prio=0 tid=0x00007fc6686b5000 nid=0x401 runnable [0x00007fc5192e8000]
java.lang.Thread.State: RUNNABLE
at com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1324)
at com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at …
```
=> junction: rewrite BlockingCalculator to be more efficient

api/src/main/java/org/killbill/billing/entitlement/EntitlementInternalApi.java, entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscriptionApi.java, entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java, entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EventsStreamBuilder.java
In 9bc87794d2f183ac92a615013ac112635e44b006, I had optimised the `getSubscriptionBundlesForAccountId` codepath, and to minimize the amount of codepaths to maintained, I had funnelled all get APIs through the same underlying methods.
Back then, our largest account known to us had 35 bundles and 67 subscriptions and this approach worked fine. Nowadays, we have accounts with over 30,000 bundles, so we need to be more mindful as to when we can _pull all by account_record_id_.
=> entitlement: pull the minimum we need in DefaultSubscriptionApi.getSubscriptionBundle

profiles/killbill/src/main/java/org/killbill/billing/server/listeners/CleanupListener.java, util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java
Enable shutdown traces and add specific traces for nodeInfo start/stop sequence.
Also see https://github.com/killbill/killbill-platform/pull/74
=> Node infos logging during start and stop sequence

util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java, util/src/main/java/org/killbill/billing/util/nodes/dao/DefaultNodeInfoDao.java, util/src/main/java/org/killbill/billing/util/nodes/dao/NodeInfoDao.java, util/src/main/java/org/killbill/billing/util/nodes/dao/NodeInfoSqlDao.java, util/src/main/resources/org/killbill/billing/util/nodes/dao/NodeInfoSqlDao.sql.stg, util/src/test/java/org/killbill/billing/util/nodes/dao/TestNodeInfoDao.java
The cleanup of the node_info entries relies on the KB shutdown sequence.
Hiwever, there is no guarantee that such shutdown sequence got initiated (e.g OOM JVM crash)
or that it terminated cleanly (k8s KILL -9 pod is takes too long), so with this change we introduce
an executor that refreshes the `updated_date` and the code has been modified to only return recent values
(updated within last 3 minutes).
=> util: Add a mechanism to not return old node_infos entries

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, NEWS, account/pom.xml, bin/start-server, catalog/pom.xml, currency/pom.xml, invoice/pom.xml, junction/pom.xml, overdue/pom.xml, payment/pom.xml, pom.xml, profiles/killbill/pom.xml, profiles/killbill/src/main/resources/update-checker/killbill-server-update-list.properties, subscription/pom.xml, util/pom.xml, util/src/test/java/org/killbill/billing/GuicyKillbillTestSuite.java, util/src/test/java/org/killbill/billing/api/AbortAfterFirstFailureListener.java, util/src/test/java/org/killbill/billing/api/FlakyInvokedMethodListener.java
Note that in order to use a more recent JVM, plugins must be re-compiled to relax the `(&(osgi.ee=JavaSE)(version=1.8))` requirement.
/cc @andrenpaes
=> Add support for more recent JDKs

profiles/killbill/src/main/java/org/apache/shiro/authc/BearerToken.java, profiles/killbill/src/main/java/org/apache/shiro/guice/web/ShiroWebModuleWith435.java, profiles/killbill/src/main/java/org/apache/shiro/web/filter/authc/BearerHttpAuthenticationFilter.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java, util/pom.xml, util/src/main/java/org/killbill/billing/util/config/definition/SecurityConfig.java, util/src/main/java/org/killbill/billing/util/glue/KillBillShiroModule.java, util/src/main/java/org/killbill/billing/util/security/api/DefaultSecurityApi.java, util/src/main/java/org/killbill/billing/util/security/shiro/realm/KillBillAuth0Realm.java, util/src/test/java/org/killbill/billing/util/security/shiro/realm/TestKillBillAuth0Realm.java
Add support for Auth0 authentication and authorization (both username/password and Bearer token).
Unfortunately, I had to copy over some of https://github.com/apache/shiro/pull/129 because of https://issues.apache.org/jira/browse/SHIRO-679 (tracked by https://github.com/killbill/killbill-oss-parent/issues/36): `BearerToken` and `BearerHttpAuthenticationFilter` (no specific logic though, can be swapped with upstream version eventually).
The Bearer filter will now be invoked first, and fallback to the Basic Auth one if there is no token.
I'll also submit a PR to update the RBAC docs.
=> shiro: initial support for Auth0

payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/ControlPluginRunner.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java, payment/src/test/java/org/killbill/billing/payment/core/sm/control/TestControlPluginRunner.java
Changes the DefaultPaymentControlContext constructor signature to accept an account id instead
of a full account. This allows to build a CallContext even if the
account is null (e.g. when processing a PSP notification).
Fixes #1472
=> Fix for #1472

api/src/main/java/org/killbill/billing/usage/DryRunTenantContext.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/FixedAndRecurringInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/UsageInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/usage/RawUsageOptimizer.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestDefaultInvoiceGenerator.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGenerator.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGeneratorWithOptimization.java, usage/src/main/java/org/killbill/billing/usage/api/svcs/DefaultInternalUserApi.java
The goal is to pass a context that looks different so the plugin can have a clue the call is made for a dry-run. This is a **hack** implementation until we get to https://github.com/killbill/killbill/issues/1468 (which requires some api changes).
The plugin would need to be configured with the following:
```
<osgi.extra-import>org.killbill.billing.usage;version=0.0.0</osgi.extra-import>
<dependency>
<groupId>org.kill-bill.billing</groupId>
<artifactId>killbill-internal-api</artifactId>
<scope>provided</scope>
</dependency>
```
Kill Bill would need to be started with the extra property:
```
org.killbill.osgi.system.bundle.export.packages.extra=org.killbill.billing.usage
```
The plugin implementor can now write some 'hack' logic to figure out if the usage call is issued from a dryRun …
=> invoice, usage: Hack around usage api to pass a hint to plugin

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoiceWithRepairLogic.java, invoice/src/main/java/org/killbill/billing/invoice/tree/NodeInterval.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestDefaultInvoiceGenerator.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGenerator.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestNodeInterval.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestSubscriptionItemTree.java
**Overview**
The method `NodeInterval#addNode` required to construct our invoice item tree based on `existing` and then `proposed` items was initially implemented  with simple use cases where various invoice items represented as `NodeInterval` were not supposed to overlap.
Starting from [this commit](https://github.com/killbill/killbill/commit/ba81d9b53173f0b09ace71cdbef018f05f914a56), we introduced the ability to split `NodeInterval` and because the tree was not generic we added preconditions in a lot of places to deal with non implemented use cases.
Then, more recently we had to implement [more cases](https://github.com/killbill/killbill/commit/c6c569d98d097301824604ac323b16cd6032df15), and then the logic to split started [to leak into the code where we were rebalancing …
=> Re-implement NodeInterval#addNode in a generic way

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationVoidInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceHardening.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceModelDao.java, invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.sql.stg, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemSqlDao.java, util/src/main/java/org/killbill/billing/util/dao/CounterMappings.java, util/src/main/java/org/killbill/billing/util/dao/CounterMappingsMapper.java, util/src/main/java/org/killbill/billing/util/glue/IDBISetup.java
The change prevents voiding invoices that have items repaired in subsequent invoices and leading to a broken state.
After this change, the void operation would be rejected, and the user would have to first void the invoice repairing the original target invoice.
Notes:
- There is currently no good information provided to help the user understanding what to void first
- There is a possibility to create a cascade of invoices to void, as each of those could have repair elements on a subsequent one - this can become problematic for larger accounts
- There is also a possibility that we cannot void the subsequent invoice with the repair items on it as it was paid -- we disallow voiding paid invoices.
=> Add handling to prevent voiding a repaired invoice. See #1464

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationVoidInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceHardening.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.java, invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.sql.stg, invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemSqlDao.java
This PR contains a series of fixes related to VOIDing invoices. This goes beyond what was originally tracked in #1464.
* New constraints:
* af237a904 Add constraints to not add items on a VOIDed invoice 
* d474c1f06544e Add constraints to avoid VOIDing an invoice with credit generation items; however, we relaxed the constraint in b02b4dd10ca9d to allow VOIDing an invoice with credit generation items when such credit was not consumed, i.e when there is enough CBA left on the account. This was added because otherwise we could end up in a situation where part or all of such credit could have been consumed and it would lead to consuming credit that does not exist (inconsistent state).
* d474c1f06544e Also contains a new contraint preventing VOIDing invoices that have `REPAIR_ADJ` items point …
=> Incremental work for 1464

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
Fix is in https://github.com/killbill/killbill/pull/1526/commits/988b5773a8cdba3f0a280683e68bb9b7e546901c
The goal is keep the dryRun (`targetDate`) behavior where we only return the last invoice for that invoice dry Run *as if everything prior that had been invoiced up to date*. So in order to also allow for a random targetDate not aligned on billing boundaries, the code need to check for that as well.
=> Work for 1503

invoice/src/main/resources/org/killbill/billing/invoice/ddl.sql, invoice/src/main/resources/org/killbill/billing/invoice/migration/V20211119130300__invoice_billing_events_index.sql
Accessing records by the `tenant_record_id` and `account_record_id` is a common pattern, but the `invoice_billing_events` table is inconsistent with other tables and does not have an index on these columns.
Add a migration file and update the ddl to add a new composite index on the `tenant_record_id` and `account_record_id` columns for the `invoice_billing_events` table.
=> add index on invoice_billing_events.{tenant_record_id, account_record_id}

profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestTag.java
I have seen the issue on CI as reported here: `https://github.com/killbill/killbill/pull/1541#issuecomment-991453841`
The issue is that when we commit an invoice, setting the CTD happens after the transaction (incl the INVOICE event) for committed,
so we need to poll for the CTD value to be correctly reflected.
=> profiles: Fix flakiness in test around CTD

payment/src/main/java/org/killbill/billing/payment/config/MultiTenantPaymentConfig.java, payment/src/main/java/org/killbill/billing/payment/core/sm/control/ControlPluginRunner.java, payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteNoDB.java, payment/src/test/java/org/killbill/billing/payment/core/sm/control/TestControlPluginRunner.java, util/src/main/java/org/killbill/billing/util/config/definition/PaymentConfig.java
By default, we only allow *setting* a new payment method from a payment control plugin.
When this new property is set to true, we allow overwriting whatever value it already had.
This needs to be used with caution, as we could have multiple updates from multiple plugins leading to a non deterministic state, or we could attempt to update a payment method for an existing `Payment` and it is not clear what the end state would be. See #1097
Also, (attempt) to fix the test instability shown below in https://github.com/killbill/killbill/pull/1559/commits/deba7f7bc43835f8e536ee08aef04dcb00a05d41
=> payment: Introduce a new property to allow updating a payment method

profiles/killbill/src/main/java/org/killbill/billing/server/filters/RequestDataFilter.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccount.java
Support utf-8 characters in audit headers by allowing them to be sent encoded.
The header `X-Killbill-Encoding` must be specified (only base64 is supported at the moment).
=> server: support for encoded audit headers

beatrix/src/test/java/org/killbill/billing/beatrix/integration/BeatrixIntegrationModule.java, catalog/pom.xml, overdue/pom.xml, profiles/killbill/src/main/java/org/killbill/billing/server/modules/JaxRSAopModule.java, profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillbillServerModule.java, profiles/killpay/pom.xml, profiles/killpay/src/main/java/org/killbill/billing/server/modules/KillpayServerModule.java, util/src/main/java/org/killbill/billing/util/config/definition/JaxrsConfig.java, util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java
When `org.killbill.jaxrs.get.ro=false` (non default), GET calls will not attempt to use the RO db connection pool, even if
configured: only plugins forcing a RO connection (via the use of `ROTenantContext`) would use it.
=> server: introduce org.killbill.jaxrs.get.ro property

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java, util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java
With this new config, we prevent failing invoice generation when past usage records seem missing
=> invoice: Add new config InvoiceConfig#isUsageMissingLenient

api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBase.java, catalog/src/test/resources/org/killbill/billing/catalog/catalogTest.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiExpire.java, util/src/test/java/org/killbill/billing/mock/MockSubscription.java
Changes for cancelPlan and changePlan processing. A few notes:
1. I've assumed that it should not be possible to cancel an expired subscription or change plan once a subscription is expired since this is in line with how cancel behaves (that is it is not possible to cancel/change a plan for a canceled subscription).
2. `cancel` require a number of tests for various scenarios (`cancel`, `cancelWithDate`, `cancelWithPolicy`, `cancelBeforeFixedTermExpiry`, `cancelAfterFixedTermExpiry`, `cancelSubscriptionWithAddOn` to name just a few). The same goes for change plan. For now, I've written only a subset of these tests in `TestUserApiExpire`. Let me know if you think we need more tests to cover some of the above scenarios and/or other scenarios that I may have missed.
1. For plan change, I've …
=> Changes for cancel and changePlan processing

api/src/main/java/org/killbill/billing/subscription/api/transfer/SubscriptionBaseTransferApi.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestBundleTransfer.java, entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java, entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApiFast.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestBundle.java, subscription/src/main/java/org/killbill/billing/subscription/api/transfer/DefaultSubscriptionBaseTransferApi.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java, subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestTransfer.java
Because of apis restrictions, we rely on plugin properties to pass this information.
The format of the (plugin properties) keys is undocumented and is subject to change in future releases; it is namespaced with `KB_` to minimize collisions with possible use cases of entitlement plugin using their own keys.
Proper fix will be introduced in `0.24` release.
=> subscription, jaxrs: Provide a (hacky) way to specify Subscription keys during transfer. See #1627

catalog/pom.xml, catalog/src/main/java/org/killbill/billing/catalog/CatalogEntityCollection.java, catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultCatalogService.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultPlanPhase.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultTier.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultUsage.java, catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultCatalogCache.java, catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultOverriddenPlanCache.java, catalog/src/main/java/org/killbill/billing/catalog/dao/DefaultCatalogOverrideDao.java, catalog/src/main/java/org/killbill/billing/catalog/glue/CatalogModule.java, catalog/src/main/java/org/killbill/billing/catalog/glue/DefaultCatalogProviderPluginRegistryProvider.java, catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java, catalog/src/main/java/org/killbill/billing/catalog/override/DefaultPriceOverride.java, catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java, catalog/src/main/java/org/killbill/billing/catalog/rules/DefaultPlanRules.java, catalog/src/test/java/org/killbill/billing/catalog/CatalogTestSuiteNoDB.java, catalog/src/test/java/org/killbill/billing/catalog/CatalogTestSuiteWithEmbeddedDB.java, catalog/src/test/java/org/killbill/billing/catalog/MockPlan.java, catalog/src/test/java/org/killbill/billing/catalog/MockProduct.java, catalog/src/test/java/org/killbill/billing/catalog/TestCatalogUpdater.java, catalog/src/test/java/org/killbill/billing/catalog/TestDefaultPriceOverride.java, catalog/src/test/java/org/killbill/billing/catalog/TestStandaloneCatalog.java, catalog/src/test/java/org/killbill/billing/catalog/TestStandaloneCatalogWithPriceOverride.java, catalog/src/test/java/org/killbill/billing/catalog/caching/TestDefaultCatalogCache.java, catalog/src/test/java/org/killbill/billing/catalog/io/TestVersionedCatalogLoader.java, catalog/src/test/java/org/killbill/billing/catalog/plugin/TestCatalogPluginMapping.java, catalog/src/test/java/org/killbill/billing/catalog/plugin/TestModelPlanRules.java, util/src/main/java/org/killbill/billing/util/io/IOUtils.java
Work for #1615 in `catalog` module. 20+ classes, but one thing that probably worth to mention is about:
``
comment in Guava dependency [pom.xml](https://github.com/killbill/killbill/compare/work-for-release-0.23.x...xsalefter:1615-killbill_catalog?expand=1#diff-19265f7f2096d2f336503b67d72a52073836d053b0e4d995875919c0f0271364L41). We able to remove guava dependency and `fast`, `slow` build is success, but I'm not sure with shade plugin. Perhaps it is just old comment?
=> 1615 killbill catalog

catalog/src/main/java/org/killbill/billing/catalog/CatalogEntityCollection.java, catalog/src/main/java/org/killbill/billing/catalog/DefaultProduct.java, catalog/src/test/java/org/killbill/billing/catalog/TestStandaloneCatalog.java, catalog/src/test/resources/org/killbill/billing/catalog/CatalogWithValidationErrors.xml
`<included>` and `<available>` product sub-sections should not reference to itself. This patch adds a validation rule to
prevent this.
For existing users, set the following System Property: `org.killbill.catalog.validation.ignoreSelfReferencingProducts=true` if modifying existing catalogs is not immediately practical.
Note: this property might be removed in a future version.
=> catalog: prevent StackOverflowError with invalid catalogs

currency/src/main/java/org/killbill/billing/currency/DefaultCurrencyProviderPluginRegistry.java, currency/src/main/java/org/killbill/billing/currency/glue/DefaultCurrencyProviderPluginRegistryProvider.java, subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/timeline/DefaultSubscriptionBaseTimelineApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/transfer/DefaultSubscriptionBaseTransferApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/engine/core/DefaultSubscriptionBaseService.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/model/SubscriptionBundleModelDao.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/model/SubscriptionModelDao.java, subscription/src/test/java/org/killbill/billing/subscription/SubscriptionTestSuiteWithEmbeddedDB.java, subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestDefaultSubscriptionTransferApi.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestSubscriptionHelper.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiCreate.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoMemory.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoSql.java, subscription/src/test/java/org/killbill/billing/subscription/engine/dao/TestSubscriptionDao.java, tenant/src/main/java/org/killbill/billing/tenant/api/TenantCacheInvalidation.java, util/src/main/java/org/killbill/billing/util/collect/MultiValueHashMap.java, util/src/main/java/org/killbill/billing/util/collect/MultiValueMap.java, util/src/test/java/org/killbill/billing/util/collect/TestMultiValueHashMap.java, util/src/test/java/org/killbill/billing/util/entity/TestDefaultPagination.java, util/src/test/java/org/killbill/billing/util/security/shiro/realm/TestKillBillJdbcRealm.java
PR for #1615 for `currency` and `subscription` modules. Things that may need attention:
- [MultiValueMap](https://github.com/killbill/killbill/compare/work-for-release-0.23.x...xsalefter:1615-currency-and-subscription?expand=1#diff-98acdefe979d09a280923cfd61679af13f1593cec1f760c638055397a4145a94) and its [implementation](https://github.com/killbill/killbill/compare/work-for-release-0.23.x...xsalefter:1615-currency-and-subscription?expand=1#diff-6ad59a0d6aaf83d6e67fbec252f6a91b982e5d7cfbac23af147999cd81c4266d), especially the collection data type that will hold the values. Is `List` enough (at least for now)? Should we use `Set` instead of `List`? Do you think naming is Ok?
- [TenantCacheInvalidation](https://github.com/killbill/killbill/compare/work-for-release-0.23.x...xsalefter:1615-curr …
=> 1615 currency and subscription

subscription/src/main/java/org/killbill/billing/subscription/api/transfer/DefaultSubscriptionBaseTransferApi.java, subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestTransfer.java
The code needs to realign the requested date with the pending start date.
This needs to happen for the cancelation of the subscription being transferred, but also transferrable events like BCD_UPDATE.
=> subscription: Fix issue when transferring pending subscription

invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceListener.java, invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceTagHandler.java, invoice/src/main/java/org/killbill/billing/invoice/ParkedAccountsManager.java, invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java, invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/main/java/org/killbill/billing/invoice/dao/CBADao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceModelDaoHelper.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceTrackingModelDao.java, invoice/src/test/java/org/killbill/billing/invoice/api/svcs/TestDefaultInvoiceInternalApiUnit.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestCBADaoUnit.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestDefaultInvoiceDaoUnit.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java, util/src/main/java/org/killbill/billing/util/collect/Iterables.java, util/src/main/java/org/killbill/billing/util/collect/Iterators.java, util/src/main/java/org/killbill/billing/util/collect/Sets.java, util/src/test/java/org/killbill/billing/util/collect/TestIterables.java, util/src/test/java/org/killbill/billing/util/collect/TestIterators.java, util/src/test/java/org/killbill/billing/util/collect/TestSets.java
I decided to create more than 1 PRs for `killbill-invoice`. For this PR, these are something that I found maybe important (and perhaps make review easier):
- `DefaultInvoiceUserApi#checkInvoiceDoesContainUsedGeneratedCredit()` : Logic changed a bit, but cross checked with `TestDefaultInvoiceUserApi#testVoidInvoice()` and result keep consistent when test running before vs after refactor.
- `CBADao#getInvoiceBalance()` : Use stream's map reduce. `TestUnitCBADao` added to test before and after refactor behavior.
- `getInvoicesByAccount#getInvoicesByAccount()` : Refactored, covered by test `TestInvoiceDao#testGetInvoicesByAccountSorted()`
- Following methods seems have a big refactor, but no. Actually I just cut the method body inside anonymous class, change it with functional style, then …
=> 1615 invoice part 1

invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceModelDao.java, invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/FixedAndRecurringInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/InvoicePruner.java, invoice/src/main/java/org/killbill/billing/invoice/tree/AccountItemTree.java, invoice/src/main/java/org/killbill/billing/invoice/tree/Item.java, invoice/src/main/java/org/killbill/billing/invoice/tree/ItemsNodeInterval.java, invoice/src/main/java/org/killbill/billing/invoice/tree/NodeInterval.java, invoice/src/main/java/org/killbill/billing/invoice/tree/SubscriptionItemTree.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestDefaultInvoiceDaoUnit.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDaoHelper.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDaoHelperUnit.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGenerator.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestSubscriptionItemTree.java, util/src/test/java/org/killbill/billing/util/collect/TestMultiValueHashMap.java
Some highlight:
- `FixedAndRecurringInvoiceItemGenerator#safetyBounds()` : Move some block inside method to dedicated methods (validateSafeBoundsWithFixedInvoiceItem(), validateSafeBoundsWithRecurringInvoiceItem()). Also change `Range` usage to Joda's `Interval`. Tests for safeBounds improved.
- `SubscriptionItemTree#mergeProposedItem()` : Refactored a little bit, but test already covered by `TestSubscriptionItemTree#testAnnualWithBlocking1()`, `TestSubscriptionItemTree#testAnnualWithBlocking2()`
- `SubscriptionItemTree#build()` : Refactored a little bit, but test already covered by current:
- `TestSubscriptionItemTree#testRepairWithLargeItemAdjustment()`, 
- `TestSubscriptionItemTree#testPartialProRation()`, 
- `TestSubscriptionItemTree#testRepairWithFullItemAdjustment()` 
- …
=> 1615 invoice part 2

invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceWithMetadata.java, invoice/src/main/java/org/killbill/billing/invoice/generator/UsageInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/model/CreditAdjInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemFactory.java, invoice/src/main/java/org/killbill/billing/invoice/model/ItemAdjInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/ParentInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/RecurringInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/RepairAdjInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/model/UsageInvoiceItem.java, invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDatePoster.java, invoice/src/main/java/org/killbill/billing/invoice/notification/NextBillingDateNotificationKey.java, invoice/src/main/java/org/killbill/billing/invoice/optimizer/InvoiceOptimizerBase.java, invoice/src/main/java/org/killbill/billing/invoice/optimizer/InvoiceOptimizerExp.java, invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java, invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceItemFormatter.java, invoice/src/main/java/org/killbill/billing/invoice/tree/ItemsInterval.java, invoice/src/main/java/org/killbill/billing/invoice/tree/TreePrinter.java, invoice/src/test/java/org/killbill/billing/invoice/InvoiceTestSuiteNoDB.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestUsageInvoiceItemGeneratorUnit.java, invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDatePoster.java, util/src/main/java/org/killbill/billing/util/Preconditions.java, util/src/main/java/org/killbill/billing/util/Strings.java, util/src/main/java/org/killbill/billing/util/collect/Iterables.java
Some notes:
- `InvoiceWithMetadata#hasItemsForSubscription()` and `InvoiceWithMetadata#hasItemsForDate()`
Exctract duplicated logic to `isInvoiceItemsMatchCondition()`
- `InvoiceOptimizerExp#filterProposedItems()`
Seems big, but actually just cut-paste. Other part of refactoring covered by unit test.
- `UsageInvoiceItemGenerator` have refactored
`TestUsageInvoiceItemGeneratorUnit` added to cover refactored method.
=> 1615 killbill invoice part 3

pom.xml
This addresses:
```
2022-05-19T15:29:57,310+0000 lvl='INFO', log='DefaultLifecycle', th='localhost-startStop-1', xff='', rId='', tok='', aRId='', tRId='', Killbill lifecycle calling handler initialize for service osgi-service
2022-05-19T15:29:57,434+0000 lvl='WARN', log='DefaultLifecycle', th='localhost-startStop-1', xff='', rId='', tok='', aRId='', tRId='', Killbill lifecycle failed to invoke lifecycle handler
java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
=> pom.xml: update to killbill-oss-parent 0.145.3-8b2bb84-SNAPSHOT

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithDryRun.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegration.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoiceWithRepairLogic.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationVoidInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceSystemDisabling.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceHardening.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTimeZones.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUnknownUsageUnits.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceDispatcher.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java, pom.xml
Depends on https://github.com/killbill/killbill-api/pull/92
We also need regenerate the java client to complete the work, but the jaxrs apis are not broken as the plugin properties are passed as query parameters. The java client signatures would change though.
=> Add ability to pass plugin properties on invoice runs. See #1471

payment/src/test/java/org/killbill/billing/payment/api/TestDefaultAdminPaymentApi.java, payment/src/test/java/org/killbill/billing/payment/api/TestDefaultPayment.java, payment/src/test/java/org/killbill/billing/payment/api/TestExternalPaymentPlugin.java, payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java, payment/src/test/java/org/killbill/billing/payment/api/TestPaymentGatewayApiWithPaymentControl.java, payment/src/test/java/org/killbill/billing/payment/core/TestPaymentMethodProcessorNoDB.java, payment/src/test/java/org/killbill/billing/payment/core/TestPaymentMethodProcessorRefreshWithDB.java, payment/src/test/java/org/killbill/billing/payment/core/TestPaymentMethodProcessorWithDB.java, payment/src/test/java/org/killbill/billing/payment/core/TestPaymentProcessor.java, payment/src/test/java/org/killbill/billing/payment/core/janitor/TestIncompletePaymentAttemptTaskWithDB.java, payment/src/test/java/org/killbill/billing/payment/core/janitor/TestIncompletePaymentTransactionTaskWithDB.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestPaymentAutomatonDAOHelper.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestPaymentEnteringStateCallback.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestPaymentLeavingStateCallback.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestPaymentOperation.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestPluginOperation.java, payment/src/test/java/org/killbill/billing/payment/core/sm/TestRetryablePayment.java, payment/src/test/java/org/killbill/billing/payment/core/sm/control/TestControlPluginRunner.java, payment/src/test/java/org/killbill/billing/payment/dao/MockPaymentDao.java, payment/src/test/java/org/killbill/billing/payment/dao/TestPaymentDao.java, payment/src/test/java/org/killbill/billing/payment/glue/TestPaymentModule.java, payment/src/test/java/org/killbill/billing/payment/provider/MockPaymentProviderPlugin.java, payment/src/test/java/org/killbill/billing/payment/provider/TestDefaultNoOpPaymentMethodPlugin.java, payment/src/test/java/org/killbill/billing/payment/provider/TestExternalPaymentProviderPlugin.java
Replace Guava and Guice usage with stream API and JSR-330 in kb-payment. This is 4th part and last PR for `killbill-payment` work for issue 1615.
=> 1615 payment part 4

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogEffectiveDate.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTerm.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogRetireElements.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEvents.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegration.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoiceWithRepairLogic.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithDifferentBillingPeriods.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPaymentWithControl.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithBCDUpdate.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithCatalogPlugin.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithFakeKPMPlugin.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithUsagePlugin.java
Some notes:
- replace `TestWithInvoiceOptimization`'s `getCurrentDraftInvoice(id, new Function() { /* co */, 10 }` to functional style `getCurrentDraftInvoice(id, input -> input.getInvoiceItems().size() == <value>, 10 }`
- add notes in `TestWithInvoiceOptimization` and other classes: `// on-1615: return value of createBaseEntitlement (entitlementId) never used, so it gets removed.` when variable is not used.
=> 1615 beatrix part 2

.github/workflows/snapshot.yml
We don't always need SNAPSHOT builds of Kill Bill core.
=> .github: don't trigger snapshot on push

subscription/src/main/java/org/killbill/billing/subscription/api/transfer/DefaultSubscriptionBaseTransferApi.java
I removed the restriction because it prevents doing transfer bundle with a future date - and I am not sure why. This is old code from 2013, perhaps we had a good reason at the time?
=> subscription: Remove unused date restriction on bundle transfer

profiles/killbill/src/main/java/org/apache/shiro/guice/web/ShiroWebModuleWith435.java, profiles/killbill/src/main/java/org/killbill/billing/server/filters/ResponseCorsFilter.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceItem.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoicePayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceVoid.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestJaxrsBase.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestJetty.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestOverdue.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentGateway.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestSecurity.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestTag.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestTenantKV.java, profiles/killbill/src/test/java/org/killbill/billing/jetty/HttpServer.java, profiles/killbill/src/test/java/org/killbill/billing/server/log/obfuscators/TestObfuscator.java, profiles/killbill/src/test/java/org/killbill/billing/server/log/obfuscators/TestObfuscatorConverter.java, profiles/killpay/pom.xml, profiles/killpay/src/main/java/org/killbill/billing/server/listeners/KillpayGuiceListener.java
This is last PR for `killbill-profiles-killbill`. Changes to `killbill-profiles-killpay` also included in this changes, because it only affected to 1 file (`KillpayGuiceListener`). 
Notes:
- `TestJaxrsBase.filterTransaction()` get removed as filter function merged into caller's stream processing, thus no longer needed.
- `ShiroWebModuleWith435` Guava's table usage removed and replaced by plain `Map<Key<? extends PathMatchingFilter>, Map<String, String>>`
=> 1615 profiles killbill part 2

entitlement/pom.xml, entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementInternalApi.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/BlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java, entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EntitlementUtils.java, entitlement/src/test/java/org/killbill/billing/entitlement/block/TestBlockingChecker.java, entitlement/src/test/java/org/killbill/billing/entitlement/dao/MockBlockingStateDao.java, entitlement/src/test/java/org/killbill/billing/entitlement/dao/TestBlockingDao.java, entitlement/src/test/java/org/killbill/billing/entitlement/dao/TestDefaultBlockingStateDao.java, junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBillingApi.java, junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBlockingCalculator.java
`BlockingStateDao.setBlockingStatesAndPostBlockingTransitionEvent()` use Guava's Optional instead of Java 8 Optional. This commit changes that, also fix affected classes. As result, Guava dependency in entitlement's `pom.xml` get removed.
=> 1615 blocking state dao

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java, entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiChangePlan.java
- Includes code changes and potential fix for #1631 
- Code changes caused `TestUserApiChangePlan.testChangePlanOnPendingSubscription` to fail, so had to change it [here](https://github.com/reshmabidikar/killbill/blob/7ec2a02332667f83bee1005e6deee076896f68a9/subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiChangePlan.java#L534).
- Code changes caused `TestDefaultEntitlementApi.testCreateBaseWithDifferentStartDate` to fail so had to change it [here](https://github.com/reshmabidikar/killbill/blob/7ec2a02332667f83bee1005e6deee076896f68a9/entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java#L679).
=> Test and potential fix for 1631

pom.xml, util/pom.xml, util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java, util/src/main/java/org/killbill/billing/util/security/shiro/realm/KillBillAuth0Realm.java, util/src/test/java/org/killbill/billing/util/security/shiro/dao/TestJDBCSessionDaoUnit.java
Affected classes: `JDBCSessionDao` and `KillBillAuth0Realm` in `killbill-util` modules.
=> 1615 replace guava cache with utils cache

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java, pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
- Added beatrix test for create subscription/change plan/cancel subscription with datetime
- Added integration test in `killbill-profiles-killbill` for `blockSubscription` with Date and DateTime (I had missed adding this earlier)
=> Beatrix test for 1375

pom.xml
Work around incorrect maven-dependency-versions-check-plugin errors with SNAPSHOT dependencies.
=> pom.xml: pin test-jar dependencies

beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestInArrearWithCatalogVersions.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUnknownUsageUnits.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInArrear.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestWithoutZeroUsageItems.java
With the changes introduced in 08f9b913b886b8e497b6edde02d51f4166137e69, we need to be more cautious when we record usage on the first day, to make sure the timestamp is not too early and usage data points is indeed taken into consideration.
For such test scenario we can use the test api `recordUsageData` which uses a DateTime and aligns with the clock value.
I did a pass on all usage tests, but this may be part of an incremental effort to fully stabilize this.
=> beatrix: Harden usage tests

catalog/src/main/java/org/killbill/billing/catalog/api/user/DefaultCatalogUserApi.java, catalog/src/test/java/org/killbill/billing/catalog/api/user/TestDefaultCatalogUserApi.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java, pom.xml
Error reporting isn't great client-side. This is tracked by https://github.com/killbill/killbill/issues/1674.
```
curl -v \
-X POST \
-u admin:password \
-H "X-Killbill-ApiKey: bob" \
-H "X-Killbill-ApiSecret: lazar" \
-H "Content-Type: text/xml" \
-H "Accept: application/json" \
-H "X-Killbill-CreatedBy: demo" \
-H "X-Killbill-Reason: demo" \
-H "X-Killbill-Comment: demo" \
-d @CatalogWithValidationErrors.xml \
"http://127.0.0.1:8080/1.0/kb/catalog/xml/validate"
{"className":"org.killbill.billing.catalog.api.CatalogApiException","code":2080,"message":"Invalid catalog for tenant : 1","causeClassName":"org.killbill.xmlloader.ValidationException","causeMessage":null,"stackTrace":[]}
```
=> catalog: add validation endpoint

beatrix/pom.xml, beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueChildParentRelationship.java, currency/pom.xml, junction/pom.xml, pom.xml, profiles/killbill/pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccount.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceItem.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentPluginProperties.java
replace all `HashMultimap`, `ImmutableMultimap`, and `Multimap` with plain `Map`. This is now possible because [this commit in killbill-client-java](https://github.com/killbill/killbill-client-java/commit/4d447749d9dd4442e3c53f5c98a0d40c7ee4a70f). this PR remove all guava classes from this repository.
Note about failed build `TestUsageInArrear#testWithUsageAtCancellationDayWithUncancel()`: I was wondering why `TestUsageInArrear` behave differently. Single test lead to failed test most of the time, but when I ran test suite, the test passed:
- Failed: `mvn -Dgroups=slow -Dtest=TestUsageInArrear#testWithUsageAtCancellationDayWithUncancel test`
- Passed: `mvn -Dgroups=slow -Dtest=TestUsageInArrear test`
But then I tried pick changes in `TestUsageInArrear` [in this …
=> 1615 use non guava killbill java client

invoice/src/test/java/org/killbill/billing/invoice/TestHtmlInvoiceGenerator.java, invoice/src/test/resources/org/killbill/billing/util/template/translation/InvoiceTranslation_en_US.properties, util/src/main/java/org/killbill/billing/util/template/translation/DefaultTranslatorBase.java, util/src/main/resources/org/killbill/billing/util/invoice/templates/HtmlInvoiceTemplate.mustache, util/src/main/resources/org/killbill/billing/util/invoice/translation/InvoiceTranslation_en_US.properties, util/src/test/java/org/killbill/billing/util/template/translation/TestDefaultTranslatorBase.java
This code wants to fix an issue encountered while working to create an invoice template and the relative translations.
In my template I added something like 
```
<div><strong>{{text.payTo}}</strong></div>
```
Even if I added the ```payTo``` property in the translation file for both the default locale (en_US) and the account locale (fr_FR) I get the error from mustache
```
"stack_trace":"org.glassfish.jersey.server.internal.process.MappableException: com.samskivert.mustache.MustacheException$Context: No method or field with name 'text.payTo' on line 46
...
```
The code wants to fix this allowing to use a new field to access any property name even when there is no a named method
In the template we will be able to use the following:
```
<div><strong>{{text.properties.payTo}}</strong></div> …
```
=> Invoice translation custom properties

api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptions.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v2.xml, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java, subscription/src/main/java/org/killbill/billing/subscription/config/MultiTenantSubscriptionConfig.java, subscription/src/main/java/org/killbill/billing/subscription/glue/DefaultSubscriptionModule.java, subscription/src/test/java/org/killbill/billing/subscription/SubscriptionTestSuiteNoDB.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestSubscriptionBillingEvents.java, util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java, util/src/main/java/org/killbill/billing/util/config/definition/SubscriptionConfig.java, util/src/test/java/org/killbill/billing/mock/MockSubscription.java, util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
* In https://github.com/killbill/killbill/commit/85a045f5a14b7112dc8a615414bd5cb8f52ecef8, there is a new test case that shows the current behavior.
* In https://github.com/killbill/killbill/commit/415c0c0a050ccf372989563688fe2c04d8fd8593, there is a prototype fix that removes the pro-ration when transition to a new Plan version.
`ci` tests fail, because the new behavior is hardcoded and in particular make the existing test `TestCatalogWithEffectiveDateForExistingSubscriptions.testRecurringPlan` fail (See TestCatalogWithEffectiveDateForExistingSubscriptions.java:120)
Notes:
- This new [method](https://github.com/killbill/killbill/pull/1663/files#diff-6c9485b2174859a0d155b69e387e4b868e364c2608ba08fd0a2db9c49101fc46R694) is very similar to [this …
=> Prototype code for #1661

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
This was breaking plugins returning binary data (e.g. zip files).
=> jaxrs: fix PluginResource encoding

account/pom.xml, beatrix/pom.xml, catalog/pom.xml, entitlement/pom.xml, invoice/pom.xml, junction/pom.xml, overdue/pom.xml, payment/pom.xml, pom.xml, profiles/killbill/pom.xml, profiles/killpay/pom.xml, subscription/pom.xml, tenant/pom.xml, usage/pom.xml, util/pom.xml
https://github.com/killbill/killbill-oss-parent/issues/619
- remove `testing-postgresql-server` and use `embedded-postgres` instead
- add `killbill-plugin-api-catalog`, otherwise get `java.lang.TypeNotPresentException: Type org.killbill.billing.catalog.plugin.api.CatalogPluginApi not present`
- remove `jersey-server` and `jersey-commons`: This is one of the problem why recent PRs in `killbill-oss-parent` fails.
=> OSS-619 use embedded postgres

util/src/test/java/org/killbill/billing/util/entity/dao/TestDefaultPaginationSqlDaoHelper.java
During debugging https://github.com/killbill/killbill/issues/1799 , where I purposely set connection pool to 1, I found that closing pagination after use helpful to make connection available.
=> close pagination after assertion completed

catalog/src/main/java/org/killbill/billing/catalog/api/user/DefaultCatalogUserApi.java, pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
Changes as per comments on https://github.com/killbill/killbill/pull/1809
=> 1674 - Changes as per review comments

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInArrearGreedySubscriptions.java, beatrix/src/test/resources/catalogs/testWithInArrearGreedySubscriptions/InArrearCatalog.xml, invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java, invoice/src/main/java/org/killbill/billing/invoice/generator/BillingIntervalDetail.java, invoice/src/main/java/org/killbill/billing/invoice/generator/FixedAndRecurringInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInAdvanceBillingIntervalDetail.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInArrearBillingIntervalDetail.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInArrearGreedyBillingIntervalDetail.java, invoice/src/test/java/org/killbill/billing/invoice/model/TestRecurringInAdvance.java, invoice/src/test/java/org/killbill/billing/invoice/model/TestRecurringInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/proRations/ProRationTestBase.java, util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java
In scenarios where we want to align RECURRING subscriptions on the day they start, and yet perform a 'bill run' later (i.e. generate all the invoices for the current month on the 1st), none of the `IN_ARREAR` nor `IN_ADVANCE` modes work very well. 
We are introducing a variation for the  `IN_ARREAR` mode which behaves just like the default use case we have, except that **when configured we allow to generate the invoice prior we reach the end of the period**. The configuration can be made at the tenant level using a new property `org.killbill.invoice.in-arrear.mode=GREEDY`.
The behavior has only been plugged for RECURRING subscriptions and not USAGE based.
Note: The PR is against our `0.22.x` `maint` branch.
=> invoice: Introduce a greedy way to charge for in-arrear subscriptions

catalog/src/test/resources/org/killbill/billing/catalog/catalogTest.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java
if the CTD is later than the current date and the plan has a billing period of NO_BILLING_PERIOD then this will cause an infinite loop
=> cancel subscription with NO_BILLING_PERIOD. fix endless cycle

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2.java, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2/Insurance-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2/Insurance-v2.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java, util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
* https://github.com/killbill/killbill/pull/1846/commits/b9309e058be85922c76a98336afb061f27e767e3 https://github.com/killbill/killbill/pull/1846/commits/2fba9e04b5bbabe500605c078251f44fc7389289: Add utility method and implement the fix
* https://github.com/killbill/killbill/pull/1846/commits/6be7adb414bbefd730456203bb9c62cf332d8f00: **Behavior change** as explained below; given the following scenario:
Two catalog versions, V1 effDt=`2022-01-01` and V2 effDt=`2022-04-01`. Plan 'P' has an `effectiveDateForExistingSubscriptions`=`2022-05-15`
0. Set the `org.killbill.subscription.align.effectiveDateForExistingSubscriptions=true` to align changes on subscription BCD
1. Start subscription on `2022-03-05`
2. Invoice up to `2022-05-05` using V1 price
The previous behavior was such that starting …
=> Fix for #1842

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java, beatrix/src/test/resources/catalogs/default/catalogTest.xml, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
The computation of the `ContiguousIntervalUsageInArrear#toEndOfDay` was not correctly taking into account
the Account#TZ. As a result, we end up creating endOfDay `transition` which are not the end of day as seen from
the customer Account.
When later in the method `ContiguousIntervalUsageInArrear#computeMissingItemsAndNextNotificationDate` we compute a LocalDate based on this endOfDay `transition`, we do not end up with the correct transition; during the next invoice run, the method `ContiguousIntervalUsageInArrear#getBilledItems` which should return the existing USAGE invoice item(s) for a given period does not find an existing item leading to a double billing of the period.
Fix is implemented in https://github.com/killbill/killbill/pull/1856/commits/96c876e53b6f84388a85529938f51311965f86 …
=> invoice: Fix usage issue for non UTC Account

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestSubscriptionBillingEvents.java
This undo the fix introduced in 42e9b205900d.
Also note that the diff in the test `TestSubscriptionBillingEvents.java` just reverts it exactly to what it currently is in `master`, so the code introduces no known behavior change aside from fixing the issue #1862
=> subscription: Rework billing events computation. See #1862

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan.java, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v2.xml, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v3.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
The tests `TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan`
showed a duplicate transition was being added in our billing events for plans with multiple phases
and where we have multiple catalog versions with `Plan#effectiveDateForExistingSubscriptions`.
The fix in place is to check that if the catalog transition was already added as part of a previous plan transition, we don't add it again. This undo the fix introduced in https://github.com/killbill/killbill/commit/f58cba4edc31ff5d407a425c268c802f2de0d63f which was removing additional transition at the end. I think it's better/cleaner to not include wrong transition in the first place.
=> subscription: Fix billing event logic for catalog transition with multi-phase plans

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans.java, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans/Insurance-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans/Insurance-v2.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java, util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
=> Initial fix for 1869

profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/PatternObfuscator.java, profiles/killbill/src/test/java/org/killbill/billing/server/log/obfuscators/TestPatternObfuscator.java
Fix for custom keywords/key-value patterns for obfuscation.  In order to use this feature, the following additional system properties need to be set:
- killbill.server.log.obfuscate.keywords (defaults to `accountnumber,authenticationdata,banknumber,bic,cardvalidationnum,cavv,ccFirstName,ccLastName,ccNumber,ccTrackData,ccVerificationValue,ccvv,cvNumber,cvc,cvv,email,iban,name,number,password,xid,externalKey`)
- killbill.server.log.obfuscate.patterns (defaults to `\\s*=\\s*'([^']+)',\\s*=\\s*"([^"]+)"`)
- killbill.server.log.obfuscate.patterns.separator (defaults to `,`)
=> Fix ts 103

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestLockingFailure.java, catalog/src/test/java/org/killbill/billing/catalog/TestCatalogService.java, invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java, overdue/src/main/java/org/killbill/billing/overdue/config/MultiTenantOverdueConfig.java, overdue/src/main/java/org/killbill/billing/overdue/glue/DefaultOverdueModule.java, overdue/src/main/java/org/killbill/billing/overdue/notification/DefaultOverdueNotifierBase.java, overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueAsyncBusNotifier.java, overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueCheckNotifier.java, overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueNotifier.java, overdue/src/main/java/org/killbill/billing/overdue/service/DefaultOverdueService.java, overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapper.java, overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapperFactory.java, overdue/src/test/java/org/killbill/billing/overdue/notification/TestOverdueCheckNotifier.java, payment/src/main/java/org/killbill/billing/payment/config/MultiTenantPaymentConfig.java, profiles/killbill/src/main/java/org/killbill/billing/server/config/MultiTenantNotificationConfig.java, subscription/src/main/java/org/killbill/billing/subscription/config/MultiTenantSubscriptionConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/KillbillConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/LockAwareConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/MultiTenantEventConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/OverdueConfig.java, util/src/main/java/org/killbill/billing/util/config/definition/PaymentConfig.java, util/src/main/java/org/killbill/billing/util/config/tenant/MultiTenantConfigBase.java, util/src/main/java/org/killbill/billing/util/config/tenant/MultiTenantLockAwareConfigBase.java, util/src/test/java/org/killbill/billing/util/config/TestTimeSpanConverter.java
This is a continuation of the work started in https://github.com/killbill/killbill/pull/1888
This PR adds the retry logic inside the overdue module when we receive a `LockFailedException`. This should conclude all the existing paths where we grab the global lock in Bill, and therefore fully address https://github.com/killbill/killbill/issues/1889
* https://github.com/killbill/killbill/pull/1894/commits/42109e4407bc51333644a9076617b03fb8b30509 adds a test to verify we correctly handle an empty config, i.e we default to not having any retry schedule. No behavior change, just a test.
* https://github.com/killbill/killbill/pull/1894/commits/8501c2a07b7c693305e51c23a75b1f453288b834 is the retry implementation for the overdue module. It adds a new `OverdueConfig` to allow configuring the retry …
=> Global lock error resiliency

jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
Support multiple key/value header pairs.
=> add nested loop for response.getHeaders() 

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceSystemDisabling.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
* 8975fea50137: Test and fix for issue #1920
* 29068811436: Modify 2 existing tests to match behavior as defined in issue - i.e an dry-run invoice with future target date only shows the items that would be returned at this time if everything is up to date, that is without items from possibly previous invoices.
=> invoice: Add fix and beatrix test for dry-run issue with blocking states

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogDiscountAndEvergreen.java, beatrix/src/test/resources/catalogs/testCatalogDiscountAndEvergreen/discount-and-evergreen.xml, subscription/src/main/java/org/killbill/billing/subscription/alignment/BaseAligner.java, subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java, subscription/src/test/java/org/killbill/billing/subscription/alignment/TestPlanAligner.java
This fixes #1923. Use case:
```
TZ=America/New_York
CREATE: 2023-03-01 03:47:56 UTC |  2023-02-28 22:47:56 NY
PHASE: 2023-06-01 03:47:56 UTC   |  2023-05-28 22:47:56 NY  (and not 2023-05-31 22:47:56 NY)
```
If we don't compute the date when adding the duration for the phase using the date in the account TZ, we end up with the wrong date, ie. `2023-06-01 03:47:56 UTC `.
Looked through the code, and did not see any other places where we add duration and need this logic of adding the duration  on the date into the account TZ
=> Fix for the computation of the phase effective date.

api/src/main/java/org/killbill/billing/callcontext/InternalCallContext.java, api/src/main/java/org/killbill/billing/callcontext/InternalTenantContext.java, api/src/main/java/org/killbill/billing/callcontext/TimeAwareContext.java, beatrix/src/test/java/org/killbill/billing/beatrix/extbus/TestBeatrixListener.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestDSTUsageIssue.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInvoicingIssue.java, beatrix/src/test/resources/catalogs/testCatalogInArrearWithRecurringAndConsumableUsage/catalogTest.xml, beatrix/src/test/resources/catalogs/testCatalogInArrearWithRecurringAndUsage/catalogTest.xml, invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/UsageClockUtil.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceTrackingSqlDao.java, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/resources/TestDBRouterResource.java, subscription/src/test/java/org/killbill/billing/subscription/alignment/TestPlanAligner.java, subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java, util/src/main/java/org/killbill/billing/util/callcontext/InternalCallContextFactory.java, util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java, util/src/test/java/org/killbill/billing/GuicyKillbillTestModule.java, util/src/test/java/org/killbill/billing/callcontext/MutableInternalCallContext.java, util/src/test/java/org/killbill/billing/util/callcontext/TestTimeAwareContext.java
We introduce a different logic for usage code to convert dates to guarantee some stability across accounts created with the same TZ but at different dates during the year (daylight saving or standard). We isolated the code in such a way that we could easily revert (or make it configurable) if needed.
=> Fix for 1934

profiles/killbill/src/main/java/org/killbill/billing/server/log/ThreadNameBasedDiscriminator.java, profiles/killbill/src/test/java/org/killbill/billing/server/log/TestThreadNameBasedDiscriminator.java
For instance, given a plugin 'myplugin', one can add an SIFT entry in the logback.xml to have the plugin split logs about jdbc. The exact name of the logfile would be of the form  `myplugin-sqltiming.<something>.out` where 'something' is based on the first stacktrace entry matching the pattern.
```
<appender name="SIFT-myplugin-sqltiming" class="ch.qos.logback.classic.sift.SiftingAppender">
<discriminator class="org.killbill.billing.server.log.ThreadNameBasedDiscriminator"/>
<sift>
<appender name="myplugin-sqltiming-${threadName}" class="ch.qos.logback.core.rolling.RollingFileAppender">
<file>${LOGS_DIR:-./logs}/myplugin-sqltiming.${threadName}.out</file>
<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
<fileNamePattern>${LOGS_DIR:-./logs}/myplugin-sqltiming-%d{yy …
```
=> profiles: Extend the existing ThreadNameBasedDiscriminator to make it usable from killbill plugins

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceFixedProration.java, invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java, invoice/src/main/java/org/killbill/billing/invoice/generator/FixedAndRecurringInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceDateUtils.java, invoice/src/main/java/org/killbill/billing/invoice/tree/AccountItemTree.java, invoice/src/main/java/org/killbill/billing/invoice/tree/Item.java, invoice/src/main/java/org/killbill/billing/invoice/tree/ItemsInterval.java, invoice/src/main/java/org/killbill/billing/invoice/tree/ItemsNodeInterval.java, invoice/src/main/java/org/killbill/billing/invoice/tree/SubscriptionItemTree.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInvoiceDateUtils.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInvoiceDateUtilsWithFixedProration.java, invoice/src/test/java/org/killbill/billing/invoice/generator/TestInvoiceDateUtilsWithoutFixedProration.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestNodeInterval.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestSubscriptionItemTree.java, invoice/src/test/java/org/killbill/billing/invoice/tree/TestTreePrinter.java, util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java
**Changes for fixed proration:**
1. Introduced a new property: `org.killbill.invoice.proration.fixed.days`
2. Added new tests: `TestInvoiceDateUtilsWithFixedProration` and `TestInvoiceDateUtilsWithoutFixedProration`
3. Tests run fine. I also did a round of manual testing via Kaui and that works fine too.
**Need your input on the following:**
The [Item](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/tree/Item.java) class also invokes the `InvoiceDateUtils.calculateProrationBetweenDates` [here](https://github.com/killbill/killbill/blob/38e4d3f0ea6d60282b4b87d7ac35341fcdd47290/invoice/src/main/java/org/killbill/billing/invoice/tree/Item.java#L154). Since this class does not have access to `InvoiceConfig`, I have passed the value `0` …
=> Changes for fixed proration

invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java, invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
Round 2 changes for #1950 
- Removed call to `invoiceApiHelper.dispatchToInvoicePluginsAndInsertItems` for `recordRefund`
- Updated `invoiceApiHelper.dispatchToInvoicePluginsAndInsertItems` to query the database and add existing invoices to the cache before invoking `dao.createInvoices`. This is so that the cache is queried for the [DefaultInvoiceUserApi.insertInvoiceItemAdjustment](https://github.com/killbill/killbill/blob/84d1e887d3203dedd381ac9b3ff3282bad155381/invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java#L409C24-L409C51) code path.
=> Changes for recordRefund and createItemAdjustment

catalog/pom.xml, invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java, invoice/src/main/java/org/killbill/billing/invoice/dao/CBADao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java, invoice/src/test/java/org/killbill/billing/invoice/dao/MockInvoiceDao.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDaoHelper.java, overdue/pom.xml
Attempt to address #1951. Some comments:
1. This is the code path: [DefaultInvoiceDao.getById](https://github.com/killbill/killbill/blob/4153f85a3e84af28c3f748dad2da50e1845eb298/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L229) --> [InvoiceDaoHelper.populateChildren](https://github.com/killbill/killbill/blob/4153f85a3e84af28c3f748dad2da50e1845eb298/invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java#L249) --> [InvoiceDaoHelper.setInvoiceRepaired](https://github.com/killbill/killbill/blob/4153f85a3e84af28c3f748dad2da50e1845eb298/invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java#L392) --> [InvoiceItemSqlDao.getRepairMap](https://github.com/killbill/killbill/blob/4153f85a3e84af28c3f748dad2da50e1845eb298/invo …
=> Changes for 1951

beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestInArrearUsagePST.java, catalog/pom.xml, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java, overdue/pom.xml
Leveraging the `UsageClockUtil` introduced to address #1966, fixed the issue right away - this is as expected since code is well encapsulated 🎉  Note that this reuses the test case introduced in eb4f9b36c18bdfd
=> Fix timezone issue for usage computation. See #1966

api/src/main/java/org/killbill/billing/util/template/translation/TranslatorConfig.java, invoice/src/main/java/org/killbill/billing/invoice/glue/DefaultInvoiceModule.java
While documenting the new properties, I realized that the `org.killbill.template.invoiceFormatterFactoryClass` property is no longer needed.  If at all a CustomInvoiceFormatter is required, it will be injected via the plugin. So only the `org.killbill.template.invoiceFormatterFactoryPluginName` property should suffice.
=> Deleted the org.killbill.template.invoiceFormatterFactoryClass property

beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestInArrearUsagePST.java, invoice/src/main/java/org/killbill/billing/invoice/usage/RawUsageOptimizer.java
The `RawUsageOptimizer#getInArrearUsage` method takes a targetDate (`LocalDate`) in the account#tz and it needs to
decide which points to pull, so it needs to be converted in a `DateTime`. We can leverage the `UsageClockUtil#toDateTimeAtEndOfDay` to get a date at the end of the day with respect to the `account#tz`, and guarantee we don't miss any points.
=> invoice: Fix issue when fetching usage points for account in non UTC. See #1981

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestAddonChangeAlignment.java, beatrix/src/test/resources/catalogs/testAddonChangeAlignment/catalog-change-alignment.xml, invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemBase.java
Includes test and fix for change add-on plan with  `START_OF_BUNDLE` alignment.
- Tests are same as those written on top of master (See https://github.com/killbill/killbill/pull/2041)
- Fix includes eliminating duplicate item
**Edit:** Added https://github.com/killbill/killbill/pull/2042/commits/5945652789868ca71f4389984e806c2a7f07c345 with 
`START_OF_SUBSCRIPTION/CHANGE_OF_PLAN` tests.
=> Work for 1739 change alignment fix

invoice/src/main/java/org/killbill/billing/invoice/usage/SubscriptionUsageInArrear.java
Reimplement RAW_USAGE_DATE_COMPARATOR to not rely on underlying `hashCode()` method. Using such method in the comparison may break the contract as there is no guarantee of unicity of a hashCode and the implementation conflicts with our equals() method.
The new implementation matches the internal `hashCode()` and `equals()` method from the `RawUsageRecord` which also looks at the 5 fields from the class.
=> invoice: Reimplement RAW_USAGE_DATE_COMPARATOR

.github/workflows/ci.yml, util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesApi.java, util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java
* Updated the logic where the current node is not found.
* Updated the node initialization logic, logging an error if a node with the same name already exists.
=> Strengthen nodes info changes

.github/workflows/ci.yml, account/src/main/java/org/killbill/billing/account/dao/DefaultAccountDao.java, api/pom.xml, api/src/main/java/org/killbill/billing/customfield/CustomFieldInternalApi.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java, beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInvoicingIssue.java, invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java, invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java, invoice/src/main/java/org/killbill/billing/invoice/dao/CBADao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java, invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java, invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDaoHelper.java, invoice/src/test/java/org/killbill/billing/invoice/optimizer/TestInvoiceOptimizerExp.java, payment/src/main/java/org/killbill/billing/payment/dao/DefaultPaymentDao.java, subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java, util/src/main/java/org/killbill/billing/util/customfield/DefaultCustomFieldInternalApi.java, util/src/main/java/org/killbill/billing/util/customfield/IntegerCustomField.java, util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldUserApi.java, util/src/main/java/org/killbill/billing/util/customfield/dao/DefaultCustomFieldDao.java, util/src/main/java/org/killbill/billing/util/entity/dao/SearchQuery.java, util/src/main/java/org/killbill/billing/util/glue/CustomFieldModule.java, util/src/test/java/org/killbill/billing/DBTestingHelper.java, util/src/test/java/org/killbill/billing/util/UtilTestSuiteWithEmbeddedDB.java, util/src/test/java/org/killbill/billing/util/customfield/TestDefaultCustomFieldInternalApi.java
Allow invoice plugins to control the invoice number by sending the plugin property INVOICE_SEQUENCE_NUMBER in getAdditionalInvoiceItems#AdditionalItemsResult.
Invoice presentment (including prefix/suffix/etc.) can be customized using an custom InvoiceFormatter in the plugin (for HTML invoices, email notifications, etc.).
=> invoice: allow custom invoice sequences

catalog/src/main/java/org/killbill/billing/catalog/dao/CatalogOverridePhaseUsageSqlDao.java, catalog/src/main/java/org/killbill/billing/catalog/dao/CatalogOverridePlanPhaseSqlDao.java, catalog/src/main/java/org/killbill/billing/catalog/dao/CatalogOverrideTierBlockSqlDao.java, catalog/src/main/java/org/killbill/billing/catalog/dao/CatalogOverrideUsageTierSqlDao.java, catalog/src/main/java/org/killbill/billing/catalog/dao/DefaultCatalogOverrideDao.java, catalog/src/main/resources/org/killbill/billing/catalog/dao/CatalogOverridePhaseUsageSqlDao.sql.stg, catalog/src/main/resources/org/killbill/billing/catalog/dao/CatalogOverridePlanPhaseSqlDao.sql.stg, catalog/src/main/resources/org/killbill/billing/catalog/dao/CatalogOverrideTierBlockSqlDao.sql.stg, catalog/src/main/resources/org/killbill/billing/catalog/dao/CatalogOverrideUsageTierSqlDao.sql.stg, catalog/src/main/resources/org/killbill/billing/catalog/ddl.sql, catalog/src/main/resources/org/killbill/billing/catalog/migration/V20240909171435__catalog_override_phase_usage_idx.sql, catalog/src/test/java/org/killbill/billing/catalog/dao/TestCatalogOverrideDao.java, catalog/src/test/java/org/killbill/billing/catalog/dao/TestCatalogOverridePhaseUsageSqlDao.java, catalog/src/test/java/org/killbill/billing/catalog/dao/TestCatalogOverridePlanPhaseSqlDao.java, catalog/src/test/java/org/killbill/billing/catalog/dao/TestCatalogOverrideTierBlockSqlDao.java, catalog/src/test/java/org/killbill/billing/catalog/dao/TestCatalogOverrideUsageTierSqlDao.java, catalog/src/test/resources/org/killbill/billing/catalog/SpyCarAdvanced.xml
This PR attempts to address some performance issues that were reported when a large number of entries have been inserted in the catalog tables to override some usage sections.
Additional tests have been written to minimize potential effect for the change on existing data but certainly not bullet proof. Details is in each commits.
⚠️ The code has not been tested against large deployment so it is a best effort based on reports.
=> Revisit catalog usage override impl

catalog/pom.xml, jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResourceHelpers.java, overdue/pom.xml, profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
There is a bug in the code due to which it is currently not possible to override a usage price by itself, it is necessary to update either a fixed or a recurring price too. This PR attempts to address this bug.
See [this comment](https://github.com/killbill/killbill-aviate-plugin/pull/287#discussion_r1886239492).
=> Fix overrides bug

.vscode/eclipse-java-killbill-style.xml, .vscode/launch.json, .vscode/settings.json, beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithUsagePlugin.java, invoice/src/main/java/org/killbill/billing/invoice/generator/UsageInvoiceItemGenerator.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java, invoice/src/main/java/org/killbill/billing/invoice/usage/RawUsageOptimizer.java, invoice/src/main/java/org/killbill/billing/invoice/usage/SubscriptionUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalCapacityInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalUsageInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestSubscriptionConsumableInArrear.java, invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java, pom.xml
The intent is to be able to communicate subscription transitions to a (usage) plugin to provide more flexibility and possibly have the plugin aggregate usage points in a way that will be **compatible** with what Kill Bill usage module expects. The new property is `USAGE_TRANSITIONS`.
In [7cea0bd](https://github.com/killbill/killbill/pull/2081/commits/7cea0bde32c2dd1e8d88a5f6d05815b5dc87ff8d), this is purely refactoring to be able to extract the computation of transitions from usage module from the usage item generation. 
In [[27570ae](https://github.com/killbill/killbill/pull/2082/commits/27570aea2fdad88638300859c7011e155506aa51)], this is the implementation to pass the new plugin property to usage plugins.
Tests: I verified the new property appears and is available from a usage plugin.
=> invoice: Implement new plugin property USAGE_TRANSITIONS for usage plugins.

beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v1.xml, beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v2.xml, subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java, util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java
In a scenario with org.killbill.subscription.align.effectiveDateForExistingSubscriptions=true, the main fix is to avoid generating a billing transition when there is no recurring section.
Also added some logic to handle NO_BILLING_PERIOD in BillCycleDayCalculator#alignToNextBillCycleDate to avoid ever entering this while loop without a way to exit it.
Added a test case that reproduces the issue.
=> Fix infinite loop issue. See #2091

util/src/main/java/org/killbill/billing/util/config/definition/ExportConfig.java, util/src/main/java/org/killbill/billing/util/export/api/DefaultExportUserApi.java, util/src/main/java/org/killbill/billing/util/export/dao/DatabaseExportDao.java, util/src/main/java/org/killbill/billing/util/glue/ExportModule.java, util/src/test/java/org/killbill/billing/util/export/dao/TestDatabaseExportDao.java, util/src/test/java/org/killbill/billing/util/export/dao/TestDatabaseExportDaoBase.java, util/src/test/java/org/killbill/billing/util/export/dao/TestDatabaseExportDaoWithAviateTables.java, util/src/test/java/org/killbill/billing/util/export/dao/TestDatabaseExportDaoWithExtraTables.java, util/src/test/java/org/killbill/billing/util/glue/TestUtilModuleWithEmbeddedDB.java
Added feature to export extra tables to address https://github.com/killbill/killbill-aviate-plugin/issues/354.  The `org.killbill.export.extra.tables.prefix` property needs to be set to the prefix of the tables that need to be exported. For the sake of simplicity, we are assuming that the extra table have the `account_id` and `tenant_id` columns. 
With regards to the ci failure, there is some leftover data in case of H2. So I've disabled some assertions for now. 
Finally, there are a lot of intermediate commits for the purpose of debugging the ci failure. So I would suggest we squash and merge this PR.
=> Export extra tables

catalog/pom.xml, invoice/src/main/java/org/killbill/billing/invoice/template/HtmlInvoiceGenerator.java, overdue/pom.xml
Handles cases when the `org.killbill.template.invoiceFormatterFactoryPluginName` property is specified but the plugin is not configured.
=> Additional null check for invoiceFormatterFactory
