killbill/killbill

- bin/db-helper
> Add getopt check for db-helper

- util/src/main/java/org/killbill/billing/util/tag/api/DefaultTagUserApi.java
- util/src/test/java/org/killbill/billing/util/tag/api/DefaultTagUserApiTest.java
> User created Tag names are now only allows in lowercase. #80

- payment/src/test/java/org/killbill/billing/payment/TestPaymentHelper.java
- payment/src/test/java/org/killbill/billing/payment/api/TestExternalPaymentPlugin.java
Verify that getPaymentInfo/getPaymentMethods works for built-in __EXTERNAL_PAYMENT__ plugin
> PR to fix #41

- profiles/killbill/src/main/java/org/killbill/billing/server/filters/RequestDataFilter.java
Keeps backward compatibility to the old "X-Killbill-Request-Id-Req" header.
> Add support for propagating the X-Request-Id header

- api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithEntilementPlugin.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementContext.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementSpecifier.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
- subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/SubscriptionEspecifier.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/SubscriptionSpecifier.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/SubscriptionDao.java
- subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoMemory.java
Involves releases to:
* killbill-api
* killbill-client-java
* killbill-plugin-api
* killbill-oss-parent
* killbill
> Combo call to create subscriptions with add-ons. #199

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
> Avoid NPE with Status#fromStatusCode

- profiles/killbill/src/test/java/org/killbill/billing/server/dao/TestEmbeddedDBFactory.java
Updates a unit test relating to the change made by https://github.com/killbill/killbill-platform/pull/15.
> Update the unit test for EmbeddedDBFactory

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestConsumableInArrear.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionUsageRecordJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestSubscriptionUsageRecordJson.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestUsage.java
- usage/src/main/java/org/killbill/billing/usage/api/user/DefaultUsageUserApi.java
- usage/src/main/java/org/killbill/billing/usage/dao/DefaultRolledUpUsageDao.java
- usage/src/main/java/org/killbill/billing/usage/dao/RolledUpUsageDao.java
- usage/src/main/java/org/killbill/billing/usage/dao/RolledUpUsageModelDao.java
- usage/src/main/java/org/killbill/billing/usage/dao/RolledUpUsageSqlDao.java
- usage/src/main/resources/org/killbill/billing/usage/dao/RolledUpUsageSqlDao.sql.stg
- usage/src/main/resources/org/killbill/billing/usage/ddl.sql
- usage/src/test/java/org/killbill/billing/usage/dao/TestDefaultRolledUpUsageDao.java
https://github.com/killbill/killbill/issues/502
> Usage API Idempotency

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
> validate usage API input

- usage/src/main/resources/org/killbill/billing/usage/ddl.sql
make (unit_type - subscription_id) fields not null in (rolled_up_usage) table
> make (unit_type - subscription_id) fields not null in (rolled_up_usage) table

- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentGatewayApi.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/ControlPluginRunner.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/PaymentControlApiAbortException.java
- payment/src/test/java/org/killbill/billing/payment/api/TestPaymentGatewayApiWithPaymentControl.java
> Make sure Abort payment exceptions are handled correctly for HPP

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceListener.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/CBADao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceModelDaoHelper.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/MockInvoiceDao.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxrsResource.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/KillbillClient.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
- util/src/test/java/org/killbill/billing/GuicyKillbillTestWithEmbeddedDBModule.java
- Integration tests for different credit scenarios.
- Fix on Parent Invoice generation.
- Child Invoice adjustment listener added.
- CBA_ADJ item generation fixed for child/parent invoices.
- Use of credit for child invoices fixed.
> Ha credit 553

- payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java
- payment/src/test/java/org/killbill/billing/payment/core/TestPaymentProcessor.java
Fix for #573
Fixes the notifyPendingPaymentOfStateChanged method for the scenario where plugin status was updated before the method is called.
> Add flag for conditionally invoking the Janitor

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/CatalogJson.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
- Added Usage Info to Phase in Catalog
- Added Integration Test to verify the behavior
- Updated OSS-Parent version to match KB Client changes
> Issue 543 - Catalog endpoint does not return usage info

- api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultPlan.java
- catalog/src/test/java/org/killbill/billing/catalog/TestCatalogUpdater.java
- catalog/src/test/resources/catalogTest.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- pom.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/addon/AddonUtils.java
- Added new control of the attribute plansAllowedInBundle, to limit the number of plans allowed per bundle (in progress)
> Issue #545 - PlansAllowedInBundle

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java
- Added method to get a Payment Transaction by Id
- Updated method in Resource to get the Payment Transaction Tags by its Id
- Added Integration Tests
> Issue #599 - Fix payment api to allow retrieving payment transaction tags

- invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java
- invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java
- pom.xml
- Changed code in DefaultInvoiceFormatter to match the new Currencies and Symbols defined in killbill-api
- Fixed Integration Tests to match the new symbols from killbill-api
> Issue 474 - Mapping currency -> locale is not unique

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentPluginProperties.java
> jaxrs: Fixes #627

- catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java
Contains speed improvements for https://github.com/killbill/killbill/issues/621.
> Use hash lookup in StandaloneCatalogMapper

- util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java
- util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionSqlDao.java
- util/src/main/java/org/killbill/billing/util/security/shiro/dao/SessionModelDao.java
- util/src/main/resources/org/killbill/billing/util/ddl.sql
- util/src/main/resources/org/killbill/billing/util/migration/V20161105000000__session_id.sql
- util/src/main/resources/org/killbill/billing/util/security/shiro/dao/JDBCSessionSqlDao.sql.stg
Issue #630 - use UUID for KillBill session id to improve security.
> Issue #630 - use UUID for KillBill session id

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentPluginProperties.java
> Fix issue #746

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/PhasePriceOverrideJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/UsagePriceOverrideJson.java
We need to display the TierBlockPolicy in our UI, so adding it to UsagePriceOverideJson :)
> Adding TierBlockPolicy to UsagePriceOverrideJson

- catalog/src/main/java/org/killbill/billing/catalog/api/user/DefaultCatalogUserApi.java
Populate account id in the call context (if available) when getting the catalog.  This was preventing the product_name, product_type, product_category from being populated correctly when using the analytics plugin.
> Fix for analytics plugin call context issue

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java
This name mismatch breaks the client parser...
> Fixed json property name

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
In case of exception when processing a new invoice (e.g. thrown by plugin),
make sure to record a notification regardless, to make sure we never stop
invoicing that account.
For review, the easiest is either to read the new code directly or to ignore whitespaces in the diff (`?w=1`).
> invoice: make sure to always record future notifications

- payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java
- payment/src/test/java/org/killbill/billing/payment/core/janitor/TestIncompletePaymentTransactionTaskWithDB.java
Fixing issue https://github.com/killbill/killbill/issues/809
@sbrossie @pierre @andrenpaes please review, thanks!
> Xqiu 20171025 fix janitor updating with outdated status

- invoice/src/main/java/org/killbill/billing/invoice/tree/SubscriptionItemTree.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceHelper.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
Follow-up on https://github.com/killbill/killbill/pull/831.
> fix NullPointerException generating invoice when there is an item adjustment for a fixed item

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/CatalogJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
This fixes https://github.com/killbill/killbill/issues/841.
Output example:
```
curl -v \
-u admin:password \
-H "X-Killbill-ApiKey: bob" \
-H "X-Killbill-ApiSecret: lazar" \
"http://127.0.0.1:8080/1.0/kb/catalog/plan?subscriptionId=25f500c4-1dac-4c58-a3c9-73996f7a8ce6&requestedDate=2018-01-01"
{
"billingPeriod": "MONTHLY",
"name": "sports-monthly",
"phases": [
{
"duration": {
"number": 30,
"unit": "DAYS"
},
"fixedPrices": [],
"prices": [],
"type": "TRIAL",
"usages": []
},
{
"duration": {
"number": -1,
"unit": "UNLIMITED"
},
"fixedPrices": [],
"prices": [
{
"currency": "GBP",
"value": 375.0
},
{
"currency": "EUR",
"value": 425.0
},
{
"currency": "USD",
"value": 500.0
},
{
"currency": "JPY",
"value": 50.0
},
{
"currency": "BTC",
"value": 0.5
}
],
"type": "EVERGREEN",
"usages": []
}
]
} …
```
> jaxrs: new APIs to retrieve catalog objects for a given subscription and date

- catalog/src/test/resources/catalogTest.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java
This fixes https://github.com/killbill/killbill/issues/840.
> entitlement: relax sanity checks for STANDALONE subscriptions

- catalog/src/main/java/org/killbill/billing/catalog/StandaloneCatalogWithPriceOverride.java
- catalog/src/test/java/org/killbill/billing/catalog/TestCatalogUpdater.java
- catalog/src/test/java/org/killbill/billing/catalog/TestStandaloneCatalogWithPriceOverride.java
- catalog/src/test/resources/SpyCarAdvanced.xml
- util/src/main/java/org/killbill/billing/util/cache/EhCacheBasedCacheController.java
This fixes https://github.com/killbill/killbill/issues/842.
> catalog: fix limitation where catalog plan name cannot end with an number

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/model/AdjInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/CreditAdjInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/CreditBalanceAdjInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/ExternalChargeInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/FixedPriceInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemBase.java
- invoice/src/main/java/org/killbill/billing/invoice/model/InvoiceItemCatalogBase.java
- invoice/src/main/java/org/killbill/billing/invoice/model/ItemAdjInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/ParentInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/RecurringInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/RepairAdjInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/TaxInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/model/UsageInvoiceItem.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
This fixes https://github.com/killbill/killbill/issues/887.
> invoice: verify we can set linked_item_id on external charges

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TestResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/Context.java
- profiles/killbill/src/main/resources/logback.xml
- util/src/main/java/org/killbill/billing/util/callcontext/InternalCallContextFactory.java
This is useful to follow bus and notifications processing.
> Add user token in MDC context

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegration.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java
This fixes https://github.com/killbill/killbill/issues/897.
> subscription: fix NPE in DefaultInternalBillingApi

- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
Found a bug in the process in `DefaultSubscriptionDao.java`.
> subscription: code review for #897

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxrsResource.java
- pom.xml
This fixes https://github.com/killbill/killbill/issues/864.
> jaxrs: remove future notifications when closing accounts

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
The response to this API call should be a list of invoices, not just a single one.
> Fix Swagger definition

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
Ref killbill/killbill-admin-ui#141
Add new endpoint to retrieve a list of catalog versions
Add query parameter `requestDate` to retrieve only one catalog xml
> Add new endpoint to retrieve a list of catalog versions; Add query parameter `requestDate` to retrieve only one catalog xml

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceListener.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceTagHandler.java
- invoice/src/main/java/org/killbill/billing/invoice/api/DefaultInvoiceContext.java
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDateNotifier.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDatePoster.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/NextBillingDateNotificationKey.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/NextBillingDatePoster.java
- invoice/src/main/java/org/killbill/billing/invoice/provider/DefaultNoOpInvoiceProviderPlugin.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceDispatcher.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceHelper.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceNotificationQListener.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDateNotificationKey.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDateNotifier.java
- pom.xml
Initial implementation for https://github.com/killbill/killbill/issues/893.
Once we agree on the semantics, I'll add tests and update dependencies (e.g. killbill-plugin-framework-java library).
> invoice: Invoice Plugin Api Enhancements

- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
Ref. killbill/killbill-api#41
Ref. killbill/killbill-admin-ui#137
> Proposed implementation to address issue killbill/killbill-admin-ui#137

- util/src/main/resources/org/killbill/billing/util/customfield/dao/CustomFieldSqlDao.sql.stg
Ref killbill/killbill-admin-ui#169
>  Custom field search should allow search on object id killbill/killbill-admin-ui#169

- .circleci/config.yml
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestEntitlementDateHelper.java
- entitlement/src/test/java/org/killbill/billing/entitlement/engine/core/TestEntitlementUtils.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/LuhnMaskingObfuscator.java
- profiles/killbill/src/test/java/org/killbill/billing/server/log/obfuscators/TestLuhnMaskingObfuscator.java
- util/src/test/java/org/killbill/billing/GuicyKillbillTestSuite.java
- util/src/test/java/org/killbill/billing/api/AbortAfterFirstFailureListener.java
- util/src/test/java/org/killbill/billing/util/audit/api/TestDefaultAuditUserApi.java
Going commit by commit might be easier:
* tests: setup fixes and CircleCI tweaks
* logging: don't obfuscate UUIDs
* entitlement: fix effective date calculation for add-ons
Note: the merge with the recent `STANDALONE` changes was quite tricky 😓 Also fixed https://github.com/killbill/killbill/commit/949d5aa9121c34b5f246b1bfa77bbd949a78ec23#r28595436.
> Tests and bug fixes

- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoicePluginDispatcher.java
Make sure to always respect the ordering specified in the config.
> invoice: fix ordering of invoice plugins

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogRetireElements.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/SubscriptionDao.java
- subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoMemory.java
See also https://github.com/killbill/killbill-integration-tests/pull/25.
> subscription: entitlement: code review

- api/src/main/java/org/killbill/billing/entitlement/EventsStream.java
- api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementSpecifier.java
- entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/transfer/DefaultSubscriptionBaseTransferApi.java
- subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestDefaultSubscriptionTransferApi.java
See https://github.com/killbill/killbill-integration-tests/pull/27.
> Entitlement fixes

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceNotifications.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDatePoster.java
- util/src/test/java/org/killbill/billing/GuicyKillbillTestSuite.java
- util/src/test/java/org/killbill/billing/util/broadcast/TestBroadcastService.java
- util/src/test/java/org/killbill/billing/util/security/shiro/realm/TestKillBillJdbcRealm.java
Trivial fix but took me forever to write the test 😅
> invoice: make sure we never insert notifications in the past

- catalog/src/main/java/org/killbill/billing/catalog/StandaloneCatalog.java
- catalog/src/main/java/org/killbill/billing/catalog/VersionedCatalog.java
- catalog/src/test/java/org/killbill/billing/catalog/TestVersionedCatalog.java
- catalog/src/test/java/org/killbill/billing/catalog/io/TestVersionedCatalogLoader.java
- catalog/src/test/resources/versionedCatalog/WeaponsHireSmall-1.xml
- catalog/src/test/resources/versionedCatalog/WeaponsHireSmall-2a.xml
- catalog/src/test/resources/versionedCatalog/WeaponsHireSmall-3.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/logging/EntitlementLoggingHelper.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java
This fixes https://github.com/killbill/killbill/issues/978.
See also https://github.com/killbill/killbill-integration-tests/pull/28.
> catalog: ability to change to a plan defined in a subsequent catalog version

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
[Reff](https://github.com/killbill/killbill/issues/980)
> AccountResource#payAllInvoices improvements

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoiceWithRepairLogic.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueIntegration.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestInvoiceFlagBehaviors.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CreditResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxrsResource.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccountTimeline.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCredit.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
TODO: Regenerate clients, add a profile test and update slack
> Fix for 827

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
* Better integration with Jooby
* Fix confusing 204 status code logging
This also fixes some typos in `InvoiceResource`.
> Plugins servlet tweaks

- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
Fix incorrect parameter for CreditAdjInvoiceItem itemDetails.
> Fix incorrect parameter for CreditAdjInvoiceItem itemDetails.

- api/src/main/java/org/killbill/billing/invoice/api/InvoiceInternalApi.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java
- invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDao.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/MockInvoiceDao.java
- payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java
- payment/src/test/java/org/killbill/billing/payment/provider/MockPaymentProviderPlugin.java
This fixes https://github.com/killbill/killbill/issues/1015.
> payment: abort invoice payment if existing payment is UNKNOWN

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentControlAwareRefresher.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentRefresher.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PluginControlPaymentAutomatonRunner.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteNoDB.java
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteWithEmbeddedDB.java
- payment/src/test/java/org/killbill/billing/payment/TestRetryService.java
- payment/src/test/java/org/killbill/billing/payment/core/TestPaymentProcessor.java
- payment/src/test/java/org/killbill/billing/payment/core/sm/MockRetryablePaymentAutomatonRunner.java
- payment/src/test/java/org/killbill/billing/payment/core/sm/TestRetryablePayment.java
This fixes #1017.
Note: the code had to move around to avoid Guice circular dependencies.
> payment: invoke control plugin state machine in Janitor GET flow

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoicePayment.java
This fixes https://github.com/killbill/killbill/issues/1014.
> jaxrs: InvoicePaymentResource#getInvoicePayment should look at unsuccessful payments

- payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java
- payment/src/main/java/org/killbill/billing/payment/provider/DefaultNoOpPaymentInfoPlugin.java
- payment/src/test/java/org/killbill/billing/payment/TestPaymentHelper.java
- payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java
- payment/src/test/java/org/killbill/billing/payment/glue/TestPaymentModule.java
- payment/src/test/java/org/killbill/billing/payment/provider/MockPaymentProviderPlugin.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java
This fixes https://github.com/killbill/killbill/issues/1038.
/cc @Ecsiral for testing
/cc @sbrossie for review
> payment: re-implement search across plugins

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
See https://github.com/killbill/killbill/issues/1042.
> Invoice dry run (TARGET_DATE mode) computes wring invoice in far future

- .idea/inspectionProfiles/Project_Default.xml
- catalog/src/main/java/org/killbill/billing/catalog/DefaultUnit.java
- catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultCatalogCache.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/mappers/RuntimeExceptionMapper.java
- util/src/main/java/org/killbill/billing/util/cache/CacheControllerDispatcherProvider.java
The main fix is the `DefaultUnit` serialization NPE. This fixes https://github.com/killbill/killbill/issues/1063.
> Fixes for 0.20.4

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithBCDUpdate.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultPlan.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/SubscriptionUsageInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalUsageInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java
* Relax `DefaultPlan` validation
* Fix usage invoicing after BCD change
> Fixes for 0.20.5

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceOffTag.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoPayOff.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
This fixes https://github.com/killbill/killbill/issues/1074.
> invoice: fix incorrect target date for non-UTC TZ

- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- pom.xml
- util/src/main/java/org/killbill/billing/util/dao/HistorySqlDao.java
- util/src/main/java/org/killbill/billing/util/entity/dao/EntityDaoBase.java
- util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDao.java
- util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoWrapperInvocationHandler.java
- util/src/main/resources/org/killbill/billing/util/entity/dao/EntitySqlDao.sql.stg
- util/src/test/java/org/killbill/billing/util/dao/TestStringTemplateInheritance.java
~⚠️ This should be looked at once https://github.com/killbill/killbill/pull/1093 is merged.~
~⚠️ **DO NOT MERGE** https://github.com/killbill/killbill-commons/pull/60 needs to be merged first.~
* Bulk insert history entries
* Optimize Batch inserts codepath: rely on `@GetGeneratedKeys` to avoid extra queries and simplify the branching in `EntitySqlDaoWrapperInvocationHandler` (code review from last PR)
> Invoice performance v5

- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/dispatcher/CallableWithRequestData.java
- util/src/main/java/org/killbill/billing/util/callcontext/InternalCallContextFactory.java
See commit by commit for bug descriptions.
> MDC logging bug fixes

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithEntilementPlugin.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultBaseEntitlementWithAddOnsSpecifier.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementContext.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscriptionApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/EntitlementPluginExecution.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementInternalApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/logging/EntitlementLoggingHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java
This also fixes logging around `targetDates` in invoice.
> Entitlement plugin api fixes

- pom.xml
This includes the queue logging changes.
> pom.xml: update to killbill-oss-parent 0.143.15

- invoice/src/main/java/org/killbill/billing/invoice/model/UsageInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalCapacityInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java
This fixes https://github.com/killbill/killbill/issues/1124.
> invoice: use rounded amount to run sanity checks

- NEWS
- invoice/src/main/java/org/killbill/billing/invoice/model/UsageInvoiceItem.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalCapacityInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestContiguousIntervalConsumableInArrear.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java
- profiles/killbill/src/main/resources/update-checker/killbill-server-update-list.properties
- profiles/killpay/src/main/resources/update-checker/killbill-server-update-list.properties
- util/src/main/java/org/killbill/billing/util/export/dao/CSVExportOutputStream.java
- util/src/test/java/org/killbill/billing/util/export/dao/TestCSVExportOutputStream.java
Signed-off-by: Pierre-Alexandre Meyer <pierre@mouraf.org>
> Merge master into work-for-release-0.21.x

- profiles/killbill/src/main/java/org/apache/shiro/authc/pam/ModularRealmAuthenticatorWith540.java
- profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java
Make sure we use our fix for https://issues.apache.org/jira/browse/SHIRO-540.
> server: fix Shiro regression

- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceTrackingSqlDao.java
The test incorrectly made some assertion from audit log targetRecordId to entity recordId -- which was incorrect
since there is a history table in between. In most cases since we only had inserts it worked but if we restart the
tests and record_id gets incremented this would break.
Also, refactor this test to have multiple transactions so we can debug what happens in this complex logic -- as opposed
to having all state in the transaction (incl. assertions and moving the clock) and nothing on disk.
> invoice: Fix issue in TestInvoiceTrackingSqlDao#testInvalidation.

- .gitignore
- account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountChangeEvent.java
- account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountCreationEvent.java
- bin/flyway-migrations
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceNotificationInternalEvent.java
- tenant/src/main/java/org/killbill/billing/tenant/api/user/DefaultTenantConfigDeletionInternalEvent.java
- util/src/main/java/org/killbill/billing/util/broadcast/DefaultBroadcastInternalEvent.java
- util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldDeletionEvent.java
* add missing `toString` methods (useful for `BeatrixListener`)
* add flyway-migrations debugging script
> Small fixes

- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionBaseCreateApi.java
This fixes https://github.com/killbill/killbill/issues/1201.
> entitlement: subscription: add error message to SUB_CREATE_INVALID_ENTITLEMENT_SPECIFIER

- subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
The work for 1215 also includes refactoring the date computation logic from entitlement and subscription module -- which is not addressed in this PR, so #1215 remains open
> Fix required for test stability

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUnknownUsageUnits.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- payment/src/main/java/org/killbill/billing/payment/core/PluginControlPaymentProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentAttemptTask.java
- payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/DefaultControlCompleted.java
- payment/src/main/java/org/killbill/billing/payment/dao/DefaultPaymentDao.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentAttemptSqlDao.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentDao.java
- payment/src/main/java/org/killbill/billing/payment/dao/PluginPropertySerializer.java
- payment/src/main/resources/org/killbill/billing/payment/dao/PaymentAttemptSqlDao.sql.stg
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteWithEmbeddedDB.java
- payment/src/test/java/org/killbill/billing/payment/TestJanitor.java
- payment/src/test/java/org/killbill/billing/payment/api/TestDefaultAdminPaymentApi.java
- payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java
- payment/src/test/java/org/killbill/billing/payment/dao/MockPaymentDao.java
- payment/src/test/java/org/killbill/billing/payment/dao/TestPaymentDao.java
* Fix for unknown usage units and tracking ids
* Fix for https://github.com/killbill/killbill/issues/1264
* Fix for https://github.com/killbill/killbill/issues/1281
> 0.20 maintenance fixes

- account/src/test/java/org/killbill/billing/account/AccountTestSuiteNoDB.java
- account/src/test/java/org/killbill/billing/account/AccountTestSuiteWithEmbeddedDB.java
- entitlement/src/test/java/org/killbill/billing/entitlement/EntitlementTestSuiteNoDB.java
- entitlement/src/test/java/org/killbill/billing/entitlement/EntitlementTestSuiteWithEmbeddedDB.java
- invoice/src/test/java/org/killbill/billing/invoice/InvoiceTestSuiteNoDB.java
- invoice/src/test/java/org/killbill/billing/invoice/InvoiceTestSuiteWithEmbeddedDB.java
- junction/src/test/java/org/killbill/billing/junction/JunctionTestSuiteNoDB.java
- junction/src/test/java/org/killbill/billing/junction/JunctionTestSuiteWithEmbeddedDB.java
- overdue/src/test/java/org/killbill/billing/overdue/OverdueTestSuiteNoDB.java
- overdue/src/test/java/org/killbill/billing/overdue/OverdueTestSuiteWithEmbeddedDB.java
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteNoDB.java
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteWithEmbeddedDB.java
- payment/src/test/java/org/killbill/billing/payment/dispatcher/TestPluginDispatcher.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestJaxrsBase.java
- subscription/src/test/java/org/killbill/billing/subscription/DefaultSubscriptionTestInitializer.java
- util/src/test/java/org/killbill/billing/util/UtilTestSuiteNoDB.java
- util/src/test/java/org/killbill/billing/util/UtilTestSuiteWithEmbeddedDB.java
The main change is in https://github.com/killbill/killbill-commons/pull/78/commits/a4a4024fd283467c7c8389a6145309bcc37776ee and https://github.com/killbill/killbill-platform/pull/64/commits/32552b88b31d11bb7d91bc72b37a30a1ed539568
> Integrate with new START_BUS lifeycle event.

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
- profiles/killbill/src/test/resources/SpyCarBasic.v2.xml
This fixes https://github.com/killbill/killbill/issues/1308.
> jaxrs: fix catalog cache corruption

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
Throwing a `RuntimeException` like it was written doesn't work well: the original exception (`CatalogApiException`) was not only masked, but it would also trigger a RST (because the exception was thrown during the Jackson serialization).
> jaxrs: rewrite BundleJson transformation

- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
PR is still WIP but you need 3cbdbb197b0797bb6cecf856e01d0142239e7f85 for your tests (as discussed last week).
> Invoice plugin API iterations

- invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceItemFormatter.java
- invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceItemFormatter.java
Per the discussion here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/killbilling-users/TWJC3INXOMc/W_TWTGaPBwAJ
> Invoice item start date is nullable on certain invoice item types

- catalog/src/main/resources/org/killbill/billing/catalog/ddl.sql
This pr cleans the ddl for the catalog module: homogenous case and indentation + added charset/collation to all tables (otherwise it is created in the default one, which might not behave as we expect)
> Cleaned up catalog ddl

- .circleci/config.yml
- beatrix/pom.xml
- invoice/src/test/resources/org/killbill/billing/util/template/translation/InvoiceTranslation_en_US.properties
- pom.xml
- profiles/killbill/pom.xml
- profiles/killbill/src/main/java/org/killbill/billing/server/listeners/CleanupListener.java
- profiles/killbill/src/main/resources/org/killbill/billing/server/version.properties
- profiles/killbill/src/main/resources/update-checker/killbill-server-update-list.properties
- profiles/killpay/pom.xml
- util/pom.xml
- util/src/main/assembly/migrator.xml
- util/src/test/java/org/killbill/billing/util/dao/TestDateInvestigation.java
- util/src/test/resources/org/killbill/billing/util/template/translation/CatalogTranslation_en_US.properties
- util/src/test/resources/org/killbill/billing/util/template/translation/CatalogTranslation_fr_CA.properties
This addresses wave 2 of killbill/killbill-oss-parent#34.
> Dependencies updates

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEvents.java
- beatrix/src/test/resources/catalogs/testCatalogWithEvents/WaterUtility-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEvents/WaterUtility-v2.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEvents/WaterUtility-v3.xml
- catalog/src/main/java/org/killbill/billing/catalog/DefaultBlock.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultPlanPhase.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultTier.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultTieredBlock.java
- catalog/src/main/java/org/killbill/billing/catalog/DefaultUsage.java
- catalog/src/test/java/org/killbill/billing/catalog/TestPlanPhase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
- profiles/killbill/src/test/resources/org/killbill/billing/server/SpyCarBasic.v2.xml
Fix issues for:
* https://github.com/killbill/killbill/issues/1396
* https://github.com/killbill/killbill/issues/1397
> Subscription events fix

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceListener.java
- invoice/src/main/java/org/killbill/billing/invoice/config/MultiTenantInvoiceConfig.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDateNotifier.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDatePoster.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/NextBillingDateNotificationKey.java
- invoice/src/main/java/org/killbill/billing/invoice/optimizer/InvoiceOptimizer.java
- invoice/src/main/java/org/killbill/billing/invoice/optimizer/InvoiceOptimizerExp.java
- invoice/src/main/java/org/killbill/billing/invoice/optimizer/InvoiceOptimizerNoop.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceNotificationQListener.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/MockInvoiceDao.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDateNotificationKey.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDateNotifier.java
- util/src/main/java/org/killbill/billing/util/config/definition/InvoiceConfig.java
* Cleanup pass in https://github.com/killbill/killbill/pull/1417/commits/225b37f6cd8875295c5175023f2ddc11a2c736cd
* New feature in https://github.com/killbill/killbill/pull/1417/commits/b1e3dff65ac281cb9e14e94b7e551364ff97ae85
> Introduce a mechanism to reschedule invoices on lock contention

- entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxrsResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
Mostly focused on optimizing the `createSubscription` path.
https://github.com/killbill/killbill/pull/1420/commits/35817dcd4dba9c2527010eacd505ef8ac05e6c33 is introduces a (non breaking) api change, i think this is the best way to address this optimization but we can discuss as needed.
> Large account optimizations

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/BundleResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CustomFieldResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentMethodResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TagResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/JaxrsUriBuilder.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccount.java
This fixes https://github.com/killbill/killbill/issues/1422.
> jaxrs: fix pagination URLs

- util/src/main/resources/cleanAccount-postgresql.sql
- util/src/main/resources/trimAccount-postgresql.sql
There isn't an easy way to share the code unfortunately.
> util: convert account procedures to PostgreSQL

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscriptionApi.java
Unfortunately, this optimization is not enough to provide the desired results, as we are [still fetching](https://github.com/killbill/killbill/blob/killbill-0.22.21/entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java#L195) the `BlockingStates` on a per account if level.
The following profiling shows the remaining issue:
```
{
"rawData": [
{
"name": "JAXRS:1.0/kb/subscriptions/fb967a17-dbff-4e46-a498-e69dd0010bb8",
"calls": [
{
"name": "API:getSubscriptionForEntitlementId",
"calls": [
{
"name": "DAO_CONNECTION:get",
"durationUsec": 57
},
{
"name": "DAO:SubscriptionSqlDao: getById",
"calls": [
{
"name": "DAO_DETAILS:SubscriptionSqlDao (raw): getById",
"durationUsec": 3570
}
],
"durationUsec": 3576
},
{
"name": "DAO:BundleSqlDao: getById",
"calls": [
{ …
```
> entitlement: Attempt at optimizing SubscriptionApi#getSubscriptionForEntitlement for large accounts

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithDryRun.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithPriceOverride.java
- catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultOverriddenPlanCache.java
- catalog/src/main/java/org/killbill/billing/catalog/caching/PriceOverridePattern.java
- catalog/src/test/java/org/killbill/billing/catalog/caching/TestPriceOverridePattern.java
- subscription/src/main/java/org/killbill/billing/subscription/catalog/SubscriptionCatalog.java
Main fix + git message is https://github.com/killbill/killbill/pull/1446/commits/dd51e963e4e78099e3d9f64bd732d23b0c45d214
> Fix issue in dry-run scenario with plan override

- payment/pom.xml
- payment/src/main/java/org/killbill/billing/payment/dao/PluginPropertySerializer.java
- payment/src/test/java/org/killbill/billing/payment/dao/TestPluginPropertySerializer.java
Verified manually with the deposit plugin.
> payment: fix serialization of DateTime

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationVoidInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceHardening.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoiceVoid.java
This fixes https://github.com/killbill/killbill/issues/1448.
> invoice: send adjustment event when voiding invoices

- entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java
With this fix, invoicing for an account with 30k+ bundles takes <10s.
> entitlement: optimize ProxyBlockingStateDao

- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
Address regression on closed-source plugins from https://github.com/killbill/killbill/pull/1488.
> invoice: make sure to pass account in context when calling plugins

- entitlement/src/main/java/org/killbill/billing/entitlement/DefaultEntitlementService.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDateNotifier.java
- invoice/src/main/java/org/killbill/billing/invoice/notification/ParentInvoiceCommitmentNotifier.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/DefaultOverdueNotifierBase.java
- payment/src/main/java/org/killbill/billing/payment/core/janitor/Janitor.java
- payment/src/main/java/org/killbill/billing/payment/retry/BaseRetryService.java
- pom.xml
- profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationRetryService.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/core/DefaultSubscriptionBaseService.java
- util/src/main/java/org/killbill/billing/util/optimizer/BusOptimizerNoop.java
- util/src/main/java/org/killbill/billing/util/optimizer/BusOptimizerOn.java
Context: https://github.com/killbill/killbill-commons/pull/97
> pom.xml: update to killbill-oss-parent 0.144.62

- pom.xml
This adds support for environment properties.
> pom.xml: update to killbill-oss-parent 0.144.63

- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
- util/src/test/resources/org/killbill/billing/util/ddl_test.sql
- Fixed TestInvoice#testInvoiceOk for new HTML template but disabled this test as it produces different output in Java 8 and Java 11. 
- Fixed test_ddl.sql
> Invoice html fix

- util/src/main/java/org/killbill/billing/util/tag/dao/DefaultTagDao.java
In normal circumstances, the tag insertion is idempotent, i.e we don't insert twice the same tag.
This is based on the https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/tag/dao/DefaultTagDao.java#L172 logic.
However, there is no account lock, so we could reach situations where we have duplicates on disk. In those scenario, the tag deletion code should remove all entries, and this is what this fix is about.
Tested manually as it is difficult to reproduce the use case.
> util: Harden tag deletion to remove duplicates if any

- util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java
In our tests, the service is created once and re-used.
Because `isStopped` wasn't reset, the underlying `nodeInfoExecutor` wasn't properly cleaned up between tests.
> util: fix DefaultKillbillNodesService for tests

- beatrix/pom.xml
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
CI seems to be _pretty_ green again!
> beatrix: fix DataSource leak in tests

- invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- Includes `InvoiceCalculatorUtils` optimizations
- Added additional tests to [TestDefaultInvoiceUserApi ](https://github.com/killbill/killbill/blob/1816bb273b79a665ecde628516bf6812dc773ad0/invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java) (Not sure if this is the right place but added a few tests that would test the changes done to `InvoiceCalculatorUtils` )
> Invoice Calculator Code Optimizations and New Tests

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java
- entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java
- entitlement/src/main/resources/org/killbill/billing/entitlement/dao/BlockingStateSqlDao.sql.stg
3 small fixes required after [previous PR](https://github.com/killbill/killbill/pull/1566)
> Billing events optimization wip

- api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java
- api/src/main/java/org/killbill/billing/subscription/api/timeline/BundleBaseTimeline.java
- entitlement/src/test/java/org/killbill/billing/entitlement/EntitlementTestSuiteWithEmbeddedDB.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/engine/core/TestEntitlementUtils.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceWithMetadata.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccountTimeline.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/timeline/DefaultSubscriptionBaseTimelineApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseBundle.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/BundleSqlDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/SubscriptionDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/SubscriptionSqlDao.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/model/SubscriptionBundleModelDao.java
- subscription/src/main/resources/org/killbill/billing/subscription/engine/dao/BundleSqlDao.sql.stg
- subscription/src/main/resources/org/killbill/billing/subscription/engine/dao/SubscriptionSqlDao.sql.stg
- subscription/src/test/java/org/killbill/billing/subscription/SubscriptionTestSuiteWithEmbeddedDB.java
- subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestTransfer.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiAddOn.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiCancel.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiChangePlan.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiError.java
- subscription/src/test/java/org/killbill/billing/subscription/engine/dao/MockSubscriptionDaoMemory.java
Ability to make one call to set all the CTDs.
The code also simplify the CTD logic by removing unused code in d4d12979a1e
> ChargeThroughDate Optimizations

- .github/workflows/ci.yml
Ruby (core) tests are running again.
> .github: add e2e job

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java
The current impl. would go through the list of all items and remove the 'item' if it is `equals` to the current one.
However, the comparison method fails, because the item may have been recreated from the plugin and would for instnance have a different `class`.
Instead, we now use the `invoiceItem#Id` to decide if this is really the same item.
The test TestWithInvoicePlugin#testUpdateDescription highlights the fix.
Also, some testing was done with an integration test.
Prior the fix, we would see an incorrect value of the CBA_ADJ (computed prior tax):
```
type    |           subscription_id            |    plan_name    | start_date |  end_date  |    amount     |    created_date
------------+--------------------------------------+-----------------+------------+------------+---------------+-- …
```
> invoice: Fix incorrect impl. of DefaultInvoice#removeInvoiceItem

- beatrix/src/main/java/org/killbill/billing/beatrix/extbus/BeatrixListener.java
- pom.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- Changes for event processing
- Deleted commented code in `DefaultSubscriptionBase` related to faking a transition
> Changes for event processing

- jaxrs/pom.xml
- pom.xml
- profiles/killbill/pom.xml
- profiles/killpay/src/main/webapp/WEB-INF/web.xml
- util/pom.xml
- util/src/main/java/org/killbill/billing/util/glue/CacheProviderBase.java
- util/src/main/java/org/killbill/billing/util/glue/Eh107CacheManagerProvider.java
- util/src/main/java/org/killbill/billing/util/glue/EhCacheProviderBase.java
- util/src/main/java/org/killbill/billing/util/glue/EhcacheShiroManagerProvider.java
- util/src/main/java/org/killbill/billing/util/glue/Redis107CacheManagerProvider.java
- util/src/main/java/org/killbill/billing/util/glue/RedisCacheProviderBase.java
- util/src/main/java/org/killbill/billing/util/glue/RedisShiroManager.java
- util/src/main/java/org/killbill/billing/util/glue/RedisShiroManagerProvider.java
- util/src/main/java/org/killbill/billing/util/metrics/JCacheGaugeFactory.java
- util/src/main/java/org/killbill/billing/util/metrics/JmxAttributeGauge.java
- util/src/test/java/org/killbill/billing/util/security/TestPermissionAnnotationMethodInterceptor.java
> Abstract away Dropwizard Metrics - bug fixes

- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
> Removed OSGI exclusions.

- account/src/main/java/org/killbill/billing/account/api/svcs/DefaultAccountInternalApi.java
- account/src/main/java/org/killbill/billing/account/api/svcs/DefaultImmutableAccountInternalApi.java
- account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountCreationEvent.java
- account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountUserApi.java
- account/src/main/java/org/killbill/billing/account/dao/AccountModelDao.java
- account/src/main/java/org/killbill/billing/account/dao/DefaultAccountDao.java
- account/src/test/java/org/killbill/billing/account/AccountTestSuiteNoDB.java
- account/src/test/java/org/killbill/billing/account/AccountTestSuiteWithEmbeddedDB.java
- account/src/test/java/org/killbill/billing/account/api/user/TestDefaultAccountUserApi.java
- account/src/test/java/org/killbill/billing/account/dao/MockAccountDao.java
- account/src/test/java/org/killbill/billing/account/dao/TestAccountDao.java
- tenant/pom.xml
- tenant/src/main/java/org/killbill/billing/tenant/api/TenantCacheInvalidation.java
- tenant/src/main/java/org/killbill/billing/tenant/api/user/DefaultTenantUserApi.java
- tenant/src/main/java/org/killbill/billing/tenant/dao/DefaultTenantDao.java
- tenant/src/main/java/org/killbill/billing/tenant/dao/NoCachingTenantDao.java
- tenant/src/test/java/org/killbill/billing/tenant/TenantTestSuiteWithEmbeddedDb.java
- tenant/src/test/java/org/killbill/billing/tenant/api/TestTenantCacheInvalidation.java
- tenant/src/test/java/org/killbill/billing/tenant/dao/TestNoCachingTenantBroadcastDao.java
- util/src/main/java/org/killbill/billing/util/entity/DefaultPagination.java
- util/src/test/java/org/killbill/billing/util/dao/TestPagination.java
PR for issue #1615 . This one for `killbill-tenant` and `killbill-account` modules. Something that may need an attention:
1. Replace Multimap with Map (and apply multi-values logic) in [TenantCacheInvalidation](https://github.com/xsalefter/killbill/blob/1e54adc77e482114e8e4f25be5801e1d5d1a6c0b/tenant/src/main/java/org/killbill/billing/tenant/api/TenantCacheInvalidation.java#L68).
2. Guava dependency [removed](https://github.com/xsalefter/killbill/blob/1e54adc77e482114e8e4f25be5801e1d5d1a6c0b/tenant/pom.xml) in `killbill-tenant`. Otherwise, build will failed.
> 1615 - killbill tenant and account modules

- .github/workflows/ci.yml
See https://github.com/actions/setup-java/issues/305.
> ci: disable Java cache

- subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestTransfer.java
See comment `https://github.com/killbill/killbill/pull/1641#discussion_r835738688`
> subscription: Enhance TestTransfer.

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestBundleTransfer.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationDryRunInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithBCDUpdate.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTimeZones.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueWithSubscriptionEOTCancellation.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/BlockingStateOrdering.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscription.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscriptionEvent.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultSubscriptionApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultSubscriptionBundleTimeline.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestRegessionSubscriptionApi.java
- entitlement/src/test/java/org/killbill/billing/entitlement/engine/core/TestEntitlementUtils.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
- pom.xml
@sbrossie, I've added a few comments where I need clarifications from you. Could you please take a look when you get a chance?
> Changes for 1375

- pom.xml
- util/src/main/java/org/killbill/billing/util/export/dao/DatabaseExportDao.java
- util/src/main/java/org/killbill/billing/util/validation/dao/DatabaseSchemaSqlDao.java
- util/src/main/resources/org/killbill/billing/util/validation/dao/DatabaseSchemaSqlDao.sql.stg
- util/src/test/java/org/killbill/billing/util/dao/TestDateInvestigation.java
- util/src/test/java/org/killbill/billing/util/export/dao/TestDatabaseExportDao.java
See https://github.com/killbill/killbill-oss-parent/pull/366 and https://github.com/killbill/killbill-commons/pull/116.
> util: support for mariadb-java-client 3.0.4

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/CatalogJson.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
- profiles/killbill/src/test/resources/org/killbill/billing/server/SpyCarBasic.v3.xml
See https://github.com/killbill/killbill/pull/1576.
> Add recurring billing mode to catalog json

- junction/pom.xml
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BlockingCalculator.java
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultBillingEvent.java
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultBillingEventSet.java
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DisabledDuration.java
- junction/src/test/java/org/killbill/billing/junction/JunctionTestSuiteNoDB.java
- junction/src/test/java/org/killbill/billing/junction/JunctionTestSuiteWithEmbeddedDB.java
- junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBillingApi.java
- junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBlockingCalculator.java
- junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestBlockingStateService.java
- junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestDefaultBillingEventSet.java
- junction/src/test/java/org/killbill/billing/junction/plumbing/billing/TestDefaultInternalBillingApi.java
> replace Guava and Guice usage with stream API and JSR-330 in kb-junction

- usage/pom.xml
- usage/src/main/java/org/killbill/billing/usage/api/BaseUserApi.java
- usage/src/main/java/org/killbill/billing/usage/api/svcs/DefaultInternalUserApi.java
- usage/src/main/java/org/killbill/billing/usage/api/user/DefaultUsageUserApi.java
- usage/src/main/java/org/killbill/billing/usage/glue/DefaultUsageProviderPluginRegistryProvider.java
Part of #1615 
I know that this should be merged with other modules as only contains 4 classes, but next module are `invoice`; I prefer invoice in dedicated PR.
> replace Guava and Guice usage with stream API and JSR-330 in kb-usage

- .github/workflows/ci.yml
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestBundleJsonWithSubscriptions.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestBundleTimelineJson.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestEntitlementJsonWithEvents.java
- pom.xml
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccountTimeline.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestUsage.java
Verifying https://github.com/killbill/killbill-integration-tests/pull/50.
> ci: point e2e tests to work-for-release-0.23.x

- pom.xml
- profiles/killbill/pom.xml
- profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestJaxrsBase.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPayment.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPlugin.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestSecurity.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestTag.java
- profiles/killbill/src/test/java/org/killbill/billing/server/security/TestTenantFilter.java
- tenant/pom.xml
- util/pom.xml
- util/src/main/java/org/killbill/billing/util/security/shiro/realm/KillBillAuth0Realm.java
- util/src/main/java/org/killbill/billing/util/security/shiro/realm/KillBillOktaRealm.java
This is part of https://github.com/killbill/killbill/issues/1640.
> server: remove AsyncHttpClient dependency

- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java
- invoice/src/main/resources/org/killbill/billing/invoice/ddl.sql
- invoice/src/main/resources/org/killbill/billing/invoice/migration/V20220429141600__invoice_group_id.sql
Addresses remaining comments from https://github.com/killbill/killbill/pull/1676
> CR Integration

- subscription/src/test/java/org/killbill/billing/subscription/api/transfer/TestTransfer.java
We verify the behavior of doing a transfer in the past prior the start date of the original subscription.
Production use case had shown some bad data being created but it looks like the fix introduced in 0a579dde34 solves the issue by realigning the dates to the start of the subscription.
> subscription: Add bundle transfer test

- invoice/src/main/java/org/killbill/billing/invoice/provider/DefaultNoOpInvoiceProviderPlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/template/HtmlInvoiceGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/template/bundles/DefaultResourceBundleFactory.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalConsumableUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/RawUsageOptimizer.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/SubscriptionUsageInArrear.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/UsageUtils.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceDispatcher.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoiceHelper.java
- invoice/src/test/java/org/killbill/billing/invoice/TestInvoicePluginDispatcher.java
- invoice/src/test/java/org/killbill/billing/invoice/api/invoice/TestDefaultInvoicePaymentApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/migration/TestDefaultInvoiceMigrationApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestInvoiceFlagBehaviors.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemSqlDao.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceTrackingSqlDao.java
- invoice/src/test/java/org/killbill/billing/invoice/glue/TestInvoiceModule.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDateNotificationKey.java
- invoice/src/test/java/org/killbill/billing/invoice/notification/TestNextBillingDatePoster.java
- invoice/src/test/java/org/killbill/billing/invoice/proRations/InvoiceTestUtils.java
- invoice/src/test/java/org/killbill/billing/invoice/tree/TestNodeInterval.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestRawUsageOptimizer.java
- invoice/src/test/java/org/killbill/billing/invoice/usage/TestUsageInArrearBase.java
- pom.xml
- util/src/main/java/org/killbill/billing/util/Joiner.java
No heavy changes. Mostly straightforward guava to stream.
> 1615 invoice part 4

- overdue/src/main/java/org/killbill/billing/overdue/applicator/OverdueStateApplicator.java
- overdue/src/main/java/org/killbill/billing/overdue/applicator/formatters/DefaultBillingStateFormatter.java
- overdue/src/main/java/org/killbill/billing/overdue/caching/OverdueCacheInvalidationCallback.java
- overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java
- overdue/src/main/java/org/killbill/billing/overdue/listener/OverdueDispatcher.java
- overdue/src/main/java/org/killbill/billing/overdue/listener/OverdueListener.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/DefaultOverduePosterBase.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueAsyncBusNotifier.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueAsyncBusPoster.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueCheckNotifier.java
- overdue/src/main/java/org/killbill/billing/overdue/notification/OverdueCheckPoster.java
- overdue/src/main/java/org/killbill/billing/overdue/service/DefaultOverdueService.java
- overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapperFactory.java
- overdue/src/test/java/org/killbill/billing/overdue/OverdueTestSuiteNoDB.java
- overdue/src/test/java/org/killbill/billing/overdue/OverdueTestSuiteWithEmbeddedDB.java
- overdue/src/test/java/org/killbill/billing/overdue/TestOverdueHelper.java
- overdue/src/test/java/org/killbill/billing/overdue/applicator/OverdueBusListenerTester.java
- overdue/src/test/java/org/killbill/billing/overdue/caching/TestDefaultOverdueConfigCache.java
- overdue/src/test/java/org/killbill/billing/overdue/notification/TestDefaultOverdueCheckPoster.java
Replace Guava and Guice usage with stream API and JSR-330 in kb-overdue. This PR for whole overdue module.
> 1615 - overdue

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/provider/DefaultNoOpInvoiceProviderPlugin.java
- pom.xml
See #1312
This has been implemented for priorCall and completion apis (similar to payment control). See https://github.com/killbill/killbill-plugin-api/pull/23
> invoice: Ability to have invoice plugins modify plugin properties. 

- payment/src/main/java/org/killbill/billing/payment/api/DefaultAdminPaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultApiBase.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultInvoicePaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultPayment.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java
- payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentGatewayApi.java
- payment/src/main/java/org/killbill/billing/payment/bus/PaymentBusEventHandler.java
- payment/src/main/java/org/killbill/billing/payment/caching/DefaultStateMachineConfigCache.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentGatewayProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentRefresher.java
- payment/src/main/java/org/killbill/billing/payment/core/ProcessorBase.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PaymentAutomatonDAOHelper.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentAttemptModelDao.java
- payment/src/test/java/org/killbill/billing/payment/core/TestPaymentRefresher.java
- pom.xml
- util/src/main/java/org/killbill/billing/util/collect/Iterables.java
- util/src/main/java/org/killbill/billing/util/collect/Iterators.java
Some notes:
1. I accidentally add sonatype snapshot repository when update parent version days ago. This PR remove it.
2. Use `MultiValueMap` instead of `MultiMap` in `PaymentRefresher`. Added test for it in `TestPaymentRefresher`.
> 1615 payment part 1

- payment/src/main/java/org/killbill/billing/payment/api/DefaultPayment.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentTransactionInfoPluginConverter.java
- payment/src/main/java/org/killbill/billing/payment/core/ProcessorBase.java
- payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentAttemptTask.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PaymentAutomatonRunner.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PaymentStateContext.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/DefaultControlCompleted.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/DefaultControlInitiated.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/control/PaymentStateControlContext.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/payments/ChargebackInitiated.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentMethodModelDao.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentModelDao.java
- payment/src/main/java/org/killbill/billing/payment/dao/PaymentTransactionModelDao.java
- payment/src/main/java/org/killbill/billing/payment/invoice/PaymentTagHandler.java
- payment/src/main/java/org/killbill/billing/payment/logging/PaymentLoggingHelper.java
- payment/src/main/java/org/killbill/billing/payment/provider/ExternalPaymentProviderPlugin.java
- payment/src/main/java/org/killbill/billing/payment/retry/BaseRetryService.java
- util/src/main/java/org/killbill/billing/util/collect/Iterables.java
- util/src/main/java/org/killbill/billing/util/collect/Iterators.java
Most of work is about refactor guava to Stream API. FYI, We'll have 1 or 2 PRs remaining for payment module.
> 1615 payment part 2

- payment/src/main/java/org/killbill/billing/payment/core/PluginControlPaymentProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PluginControlPaymentAutomatonRunner.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/payments/PaymentOperation.java
- payment/src/main/java/org/killbill/billing/payment/dao/DefaultPaymentDao.java
- payment/src/main/java/org/killbill/billing/payment/dispatcher/PaymentPluginDispatcher.java
- payment/src/main/java/org/killbill/billing/payment/dispatcher/PluginDispatcher.java
- payment/src/main/java/org/killbill/billing/payment/glue/PaymentModule.java
- payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java
- payment/src/main/java/org/killbill/billing/payment/provider/DefaultNoOpGatewayNotification.java
- payment/src/main/java/org/killbill/billing/payment/provider/DefaultNoOpHostedPaymentPageFormDescriptor.java
- payment/src/main/java/org/killbill/billing/payment/provider/DefaultNoOpPaymentInfoPlugin.java
- payment/src/main/java/org/killbill/billing/payment/provider/DefaultNoOpPaymentMethodPlugin.java
- payment/src/main/java/org/killbill/billing/payment/provider/ExternalPaymentProviderPlugin.java
- payment/src/test/java/org/killbill/billing/payment/MockInvoice.java
- payment/src/test/java/org/killbill/billing/payment/PaymentTestSuiteNoDB.java
- payment/src/test/java/org/killbill/billing/payment/TestDefaultStateMachineConfigDOTGenerator.java
- payment/src/test/java/org/killbill/billing/payment/TestJanitor.java
- payment/src/test/java/org/killbill/billing/payment/TestPaymentHelper.java
- payment/src/test/java/org/killbill/billing/payment/TestRetryService.java
- payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApiNoDB.java
- payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApiWithControl.java
- payment/src/test/java/org/killbill/billing/payment/caching/TestStateMachineConfigCache.java
- payment/src/test/java/org/killbill/billing/payment/dao/TestDefaultPaymentDao.java
- payment/src/test/java/org/killbill/billing/payment/invoice/TestInvoicePaymentControlPluginApiUnit.java
- payment/src/test/java/org/killbill/billing/payment/logging/SpyLogger.java
This is 3rd part of killbill-payment work for issue 1615.
> 1615 payment part 3

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogNewEntries.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- entitlement/src/main/java/org/killbill/billing/entitlement/logging/EntitlementLoggingHelper.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- pom.xml
1375 - Added method for changePlan
> Work for release 0.23 1375 change plan

- beatrix/src/test/java/org/killbill/billing/beatrix/BeatrixTestSuiteWithEmbeddedDB.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogPlanAligner.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithDryRun.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptions.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestHardenCatalogPlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithCatalogUpdate.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceNotifications.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoicePayment.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPaymentRefund.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestTagApi.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithPriceOverride.java
- beatrix/src/test/java/org/killbill/billing/beatrix/util/InvoiceChecker.java
- beatrix/src/test/java/org/killbill/billing/beatrix/util/PaymentChecker.java
- beatrix/src/test/java/org/killbill/billing/beatrix/util/RefundChecker.java
> 1615 Beatrix part 1

- beatrix/src/main/java/org/killbill/billing/beatrix/extbus/BeatrixListener.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/BeatrixIntegrationModule.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestBundleTransfer.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogAvailableAddOns.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTermWithVersionedCatalogs.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogValidation.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptions2.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationVoidInvoice.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithAutoInvoiceDraft.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithWrittenOffTag.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInvoiceSystemDisabling.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestMigrationSubscriptions.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPublicBus.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInArrearSubscriptions.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceHardening.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTaxItems.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithTimeZones.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/db/TestDBRouter.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueIntegration.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestInArrearWithCatalogVersions.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUnknownUsageUnits.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInArrear.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestWithoutZeroUsageItems.java
Last PR for `killbill-beatrix`
> 1615 beatrix part 3

- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/CatalogJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/JsonBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/ProfilingDataJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/BundleResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CustomFieldResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginInfoResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TagDefinitionResource.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestJaxRsResourceBase.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestOverdueResource.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestUsageResource.java
- util/src/main/java/org/killbill/billing/util/Strings.java
- util/src/main/java/org/killbill/billing/util/tag/api/DefaultTagUserApi.java
- util/src/test/java/org/killbill/billing/TestStrings.java
Some notes:
- [JaxRsResourceBase.deleteCustomFields()](https://github.com/killbill/killbill/blob/cef3351c4ec44347d478f61e420ae8d443fc62f8/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L300), add small logic `customFieldList == null` to match specs in javadoc, " .... or null if they should all be removed"
- Move `TestJaxRsResourceBase.testGetHighestRecordDate()` to `TestUsageResource.testGetHighestRecordDate()`
- extract `BundleResource.getBundles()` and `BundleResource.searchBundles()` methods to `buildBundleStreamPaginationResponse()` because they are contains (almost) the same method body.
> 1615 jaxrs part 2

- catalog/pom.xml
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- overdue/pom.xml
The account balance wasn't always accurate when some invoices were written off.
> invoice: fix regression from a47ba879138d7b2b966c4e8afb192c6a5bb14e6c

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CreditResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/NodesInfoResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentGatewayResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentMethodResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TagResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TestResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/Context.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/JaxrsUriBuilder.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/KillbillEventHandler.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestInvoiceResource.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestPaymentMethodResource.java
- `InvoiceResource` : 
- Extract same logic in `getInvoices()` and `searchInvoices()` to `buildInvoicesStreamingPaginationResponse()`
- Extract same logic in `getInvoice()`, `getInvoiceByItemId()` and `getInvoiceByNumber()` to `buildGetInvoiceWithItemResponse()`
- `NodeInfosResouce` : extract block in `getNodesInfo()` to new private methods (`mapPluginInfoToJson()` and `mapNodeInfoToJson()`).
- `PaymentMethodResource`: 
- Extract same logic in `getPaymentMethods()` and `searchPaymentMethods()` to `buildPaymentMethodsStreamingPaginationResponse()`
- Extract same logic in `getPaymentMethod()` and `getPaymentMethodByKey()` to `buildPaymentMethodResponse()`
- `TagResource` : extract same logic in `getTags()` and `searchTags()` to `buildTagsStreamingPaginationResponse()`
> 1615 jaxrs part 3

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/ExportResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResourceHelpers.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/JaxrsTestSuiteNoDB.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestBundleJsonWithSubscriptions.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestBundleTimelineJson.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestEntitlementJsonWithEvents.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestInvoiceJsonWithBundleKeys.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/json/TestTagDefinitionJson.java
- jaxrs/src/test/java/org/killbill/billing/jaxrs/resources/TestOverdueResource.java
This is last PR of killbill-jaxrs for issue 1615.
> 1615 jaxrs part 4

- profiles/killbill/src/main/java/org/killbill/billing/server/filters/RequestDataFilter.java
- profiles/killbill/src/main/java/org/killbill/billing/server/filters/ResponseCorsFilter.java
- profiles/killbill/src/main/java/org/killbill/billing/server/listeners/KillbillGuiceListener.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/ConfigMagicObfuscator.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/LoggingFilterObfuscator.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/LuhnMaskingObfuscator.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/Obfuscator.java
- profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/PatternObfuscator.java
- profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java
- profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java
- profiles/killbill/src/main/java/org/killbill/billing/server/security/TenantFilter.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/CallbackServlet.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/KillbillClient.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAccount.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestAdmin.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestBundle.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCache.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestChargeback.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCustomField.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestExternalRefund.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestPaymentPluginProperties.java
- profiles/killbill/src/test/java/org/killbill/billing/server/filters/TestRequestDataFilter.java
- util/src/main/java/org/killbill/billing/util/net/HttpHeaders.java
Notes:
- Some logic inside`RequestDataFilter.filter(ContainerRequestContext)` changed. Added test case to proof that previous and current behavior still the same.
- Added new notes `// FIXME-1615 : killbill-client-java : RequestOptions using MultiMap`
> 1615 killbill-profiles-killbill part 1

- account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountUserApi.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
- payment/src/main/java/org/killbill/billing/payment/core/PaymentRefresher.java
- subscription/pom.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- util/src/main/java/org/killbill/billing/util/cache/CacheController.java
- util/src/main/java/org/killbill/billing/util/cache/KillBillCacheController.java
- util/src/main/java/org/killbill/billing/util/cache/NoOpCacheController.java
- util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldUserApi.java
- util/src/main/java/org/killbill/billing/util/entity/dao/DefaultPaginationHelper.java
- util/src/main/java/org/killbill/billing/util/tag/api/DefaultTagUserApi.java
Replace Guava's Function with java 8 Function in these places:
- `CacheController`
- `DefaultPaginationHelper`
As a result, guava dependency in `subscription` pom.xml get removed.
> 1615 remove guava function

- account/pom.xml
- account/src/test/java/org/killbill/billing/account/api/user/TestDefaultAccountUserApi.java
- beatrix/pom.xml
- beatrix/src/main/java/org/killbill/billing/beatrix/extbus/BeatrixListener.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPublicBus.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithFakeKPMPlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/db/TestDBRouter.java
- invoice/pom.xml
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceListener.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceTagHandler.java
- jaxrs/pom.xml
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/KillbillEventHandler.java
- overdue/pom.xml
- overdue/src/main/java/org/killbill/billing/overdue/listener/OverdueListener.java
- overdue/src/test/java/org/killbill/billing/overdue/applicator/OverdueBusListenerTester.java
- payment/pom.xml
- payment/src/main/java/org/killbill/billing/payment/bus/PaymentBusEventHandler.java
- payment/src/main/java/org/killbill/billing/payment/invoice/PaymentTagHandler.java
- payment/src/test/java/org/killbill/billing/payment/core/TestPaymentProcessor.java
- pom.xml
- profiles/killbill/pom.xml
- profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java
- util/pom.xml
- util/src/test/java/org/killbill/billing/api/TestApiListener.java
- replace `Subscribe` and `AllowConcurrentEvents`
- remove guava dependency in several modules.
> 1615 replace guava eventbus with util eventbus

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestSubscription.java
- entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiChangePlan.java
> Work for release 0.23.x promotion

- api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogForcedPhaseChangeWithDryRun.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptions.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java
- beatrix/src/test/resources/catalogs/testCatalogForcedPhaseChange/WeaponsHireSmall-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig/Insurance-v2.xml
- invoice/src/test/java/org/killbill/billing/invoice/TestHtmlInvoiceGenerator.java
- invoice/src/test/resources/org/killbill/billing/util/template/translation/InvoiceTranslation_en_US.properties
- subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionApiBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/config/MultiTenantSubscriptionConfig.java
- subscription/src/main/java/org/killbill/billing/subscription/glue/DefaultSubscriptionModule.java
- subscription/src/test/java/org/killbill/billing/subscription/SubscriptionTestSuiteNoDB.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestDefaultSubscriptionBase.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestSubscriptionBillingEvents.java
- util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java
- util/src/main/java/org/killbill/billing/util/config/definition/SubscriptionConfig.java
- util/src/main/java/org/killbill/billing/util/template/translation/DefaultTranslatorBase.java
- util/src/main/resources/org/killbill/billing/util/invoice/templates/HtmlInvoiceTemplate.mustache
- util/src/main/resources/org/killbill/billing/util/invoice/translation/InvoiceTranslation_en_US.properties
- util/src/test/java/org/killbill/billing/mock/MockSubscription.java
- util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
- util/src/test/java/org/killbill/billing/util/template/translation/TestDefaultTranslatorBase.java
@sbrossie @reshmabidikar do you mind to review my merge changes especially for 
- [SubscriptionApiBase](https://github.com/killbill/killbill/pull/1778/files#diff-699f89a95013c79d65f3a2489c333b27c2dc0d176b9ef086afad26a71dbaf997)
- [DefaultSubscriptionBase](https://github.com/killbill/killbill/pull/1778/files#diff-6c9485b2174859a0d155b69e387e4b868e364c2608ba08fd0a2db9c49101fc46)
- [SubscriptionBaseApiService](https://github.com/killbill/killbill/pull/1778/files#diff-7db4ffeb96edd7d1fdfbbfb0193eb65ae5a88db6932092a7424c2e9bb2f330dd)
I also add `FIXME` for various changes that I made but not sure if that's what expected. For example, [this one](https://github.com/killbill/killbill/pull/1778/files#diff-39b9f6d3a9fd8f86565a96058830f6184e1c3d62938aa6e685e6bd420d91e08f).
> Merge master to work for release 0.23.x

- beatrix/src/main/java/org/killbill/billing/beatrix/extbus/BeatrixListener.java
- beatrix/src/test/java/org/killbill/billing/beatrix/extbus/TestBeatrixListener.java
- pom.xml
@pierre @reshmabidikar 
Kindly review
> Code for TenantConfig and Tag Metadata

- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
> profile: Harden test TestInvoice#testKB_REUSE_DRAFT_INVOICING_ID

- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestInvoice.java
See previous [PR](https://github.com/killbill/killbill/pull/1811)
> Fix ci failure

- catalog/src/main/java/org/killbill/billing/catalog/api/user/DefaultCatalogUserApi.java
- profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestCatalog.java
Changes to clone catalog as per @pierre's comment [here](https://github.com/killbill/killbill/pull/1809#discussion_r1040812211).
> 1674 - Changes to clone catalog

- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/SubscriptionBuilder.java
Minor fixes to get [Aviate Quote Issue#14](https://github.com/killbill/killbill-aviate-plugin/issues/14) to work.
> Minor fixes

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2.java
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2/Insurance-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig2/Insurance-v2.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java
- util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
This is a backport of https://github.com/killbill/killbill/pull/1846 on top of maint-for-0.22.x
> Maint for 0.22.x 1661 fix

- api/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementSpecifier.java
- spotbugs-exclude.xml
- util/pom.xml
- util/src/main/java/org/killbill/billing/util/PluginProperties.java
- util/src/main/java/org/killbill/billing/util/broadcast/DefaultBroadcastInternalEvent.java
- util/src/main/java/org/killbill/billing/util/cache/KillBillCacheController.java
- util/src/main/java/org/killbill/billing/util/config/tenant/PerTenantConfig.java
- util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldCreationEvent.java
- util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldDeletionEvent.java
- util/src/main/java/org/killbill/billing/util/customfield/dao/DefaultCustomFieldDao.java
- util/src/main/java/org/killbill/billing/util/dao/DefaultNonEntityDao.java
- util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoTransactionalJdbiWrapper.java
- util/src/main/java/org/killbill/billing/util/export/dao/CSVExportOutputStream.java
- util/src/main/java/org/killbill/billing/util/export/dao/DatabaseExportDao.java
- util/src/main/java/org/killbill/billing/util/nodes/json/PluginInfoModelJson.java
- util/src/main/java/org/killbill/billing/util/security/api/DefaultSecurityApi.java
- util/src/main/java/org/killbill/billing/util/security/shiro/dao/JDBCSessionDao.java
- util/src/main/java/org/killbill/billing/util/validation/ValidationManager.java
- util/src/test/java/org/killbill/billing/util/broadcast/TestDefaultBroadcastInternalEvent.java
- util/src/test/java/org/killbill/billing/util/customfield/api/TestDefaultCustomFieldCreationEvent.java
- util/src/test/java/org/killbill/billing/util/customfield/api/TestDefaultCustomFieldDeletionEvent.java
Attempt to fix this issue: https://github.com/killbill/killbill/issues/1853 . Most commits in this PR represents issues that attempt to fix. Some PRs that may need an attention:
-  add equals/hashcode that refers to superclass to fix eq_doesnt_override_equals: https://github.com/killbill/killbill/commit/8cef8bb8dc4d605c129b998ba4499376c76077cc
- use getClass() in equals method to fix EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC: https://github.com/killbill/killbill/commit/67ee5064243375bdff859e6528ee10f421d0f031 and https://github.com/killbill/killbill/commit/e0cfea8459b1c90a96f8c47e089e4605b4637d0d
- use AND operator (&&) instead of non-short-circuit logic (&) : https://github.com/killbill/killbill/commit/536667363134f1cdebb416bff95b6961b5c61651
> fix spotbugs in api and util

- spotbugs-exclude.xml
- subscription/pom.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java
- subscription/src/main/java/org/killbill/billing/subscription/api/timeline/DefaultSubscriptionBaseTimeline.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBillingEvent.java
- subscription/src/main/java/org/killbill/billing/subscription/api/user/SubscriptionBaseTransitionDataIterator.java
- subscription/src/main/java/org/killbill/billing/subscription/catalog/SubscriptionCatalog.java
- subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java
- subscription/src/main/java/org/killbill/billing/subscription/events/EventBase.java
- subscription/src/test/java/org/killbill/billing/subscription/events/bcd/TestBCDEventData.java
Fix this issue: https://github.com/killbill/killbill/issues/1853 . Each commits represent what its attempt to fix.
> fix spotbugs in subscription module

- entitlement/pom.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/api/BlockingStateOrdering.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultBlockingTransitionInternalEvent.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultSubscriptionApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementInternalApi.java
- entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java
- entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EntitlementUtils.java
- entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EventsStreamBuilder.java
- usage/pom.xml
- usage/src/main/java/org/killbill/billing/usage/api/BaseUserApi.java
- usage/src/main/java/org/killbill/billing/usage/api/user/DefaultUsageUserApi.java
Fix this issue: https://github.com/killbill/killbill/issues/1853 . Each commits represent what its attempt to fix.
> fix spotbugs in entitlement and usage

- beatrix/pom.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java
- jaxrs/pom.xml
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/AccountTimelineJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/BlockPriceJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/BlockingStateJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/GatewayNotificationJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/JsonBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/OverdueConditionJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/ProfilingDataJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/json/TagDefinitionJson.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/OverdueResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TenantResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TestResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/UsageResource.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/Context.java
- jaxrs/src/main/java/org/killbill/billing/jaxrs/util/JaxrsUriBuilder.java
- spotbugs-exclude.xml
- util/src/main/java/org/killbill/billing/util/nodes/json/PluginInfoModelJson.java
Fix this issue: https://github.com/killbill/killbill/issues/1853 for `beatrix` and `jaxrs` modules. Each commits represent what its attempt to fix. Some commits may need more attention:
- [remove unused local variables](https://github.com/killbill/killbill/commit/d83c13e637bab0862505282ae23fbf470e897062)
- [use DateTimeZone.UTC if account.getTimeZone() is null](https://github.com/killbill/killbill/commit/576803ed6a0b89970203c21e52c44ff6ade7a0ad)
- [remove try-catch block to NullPointerException](https://github.com/killbill/killbill/commit/09781d15977a513975945a75e31998317a1ac2e1)
> fix spotbugs in beatrix and jaxrs

- api/pom.xml
- api/src/main/java/org/killbill/billing/overdue/config/api/BillingState.java
- api/src/main/java/org/killbill/billing/util/UUIDs.java
- invoice/pom.xml
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceBillingEventModelDao.java
- invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java
- profiles/killbill/pom.xml
- profiles/killbill/src/main/java/org/apache/shiro/guice/web/ShiroWebModuleWith435.java
- profiles/killbill/src/main/java/org/killbill/billing/server/filters/RequestDataFilter.java
- profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java
- profiles/killpay/pom.xml
- spotbugs-exclude.xml
Fix this issue: https://github.com/killbill/killbill/issues/1853 for `profiles` modules. Each commits represent what its attempt to fix.
> Kb 1853 fix spotbugs in profiles

- account/pom.xml
- api/pom.xml
- beatrix/pom.xml
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfig.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoiceOptimization.java
- beatrix/src/test/resources/catalogs/default/catalogTest.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v2.xml
- catalog/pom.xml
- currency/pom.xml
- entitlement/pom.xml
- invoice/pom.xml
- invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalUsageInArrear.java
- jaxrs/pom.xml
- junction/pom.xml
- overdue/pom.xml
- payment/pom.xml
- pom.xml
- profiles/killbill/pom.xml
- profiles/killpay/pom.xml
- profiles/pom.xml
- subscription/pom.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- subscription/src/test/java/org/killbill/billing/subscription/api/user/TestSubscriptionBillingEvents.java
- tenant/pom.xml
- usage/pom.xml
- util/pom.xml
See https://github.com/killbill/killbill/issues/1862.
> Fix for price changes and multi-phase plans

- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
> https://github.com/killbill/killbill/issues/1863

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan.java
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v2.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
Port fix from 0.24 for issue #1862. See 0.24 PRs:
* https://github.com/killbill/killbill/pull/1873
* https://github.com/killbill/killbill/pull/1872
Note that initial port introduced an issue was was fixed in https://github.com/killbill/killbill/pull/1874/commits/a37e39ca4cf6ffaf54819e4fe33bd4b77855e65c
> Maint for 0.22.x fix 1862

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan.java
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v2.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigMultiPhasePlan/Insurance-v3.xml
> Additional tests

- catalog/pom.xml
- overdue/pom.xml
applied to overdue and catalog pom.xml
> set createDependencyReducedPom=false

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
Pass plugin properties thru for invoice dry-runs so they can be used by invoice plugins.
> Dry run plugin property fix

- api/src/main/java/org/killbill/billing/usage/InternalUserApi.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithUsagePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/FixedAndRecurringInvoiceItemGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/InvoiceItemGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/generator/UsageInvoiceItemGenerator.java
- invoice/src/main/java/org/killbill/billing/invoice/usage/RawUsageOptimizer.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java
- invoice/src/test/java/org/killbill/billing/invoice/generator/TestDefaultInvoiceGenerator.java
- invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGenerator.java
- invoice/src/test/java/org/killbill/billing/invoice/generator/TestFixedAndRecurringInvoiceItemGeneratorWithOptimization.java
- usage/src/main/java/org/killbill/billing/usage/api/svcs/DefaultInternalUserApi.java
invoice: Fix wiring to correctly pass plugin properties to usage plugin on invoice dry run calls.
> Fix for #1883

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestAllowPaymentForEmptyInvoice.java
- payment/src/main/java/org/killbill/billing/payment/config/MultiTenantPaymentConfig.java
- payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java
- util/src/main/java/org/killbill/billing/util/config/definition/PaymentConfig.java
Fix for [TS#100](https://github.com/killbill/technical-support/issues/100) (Allow empty invoice)
> Changes for allow empty invoice

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans.java
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans/Insurance-v1.xml
- beatrix/src/test/resources/catalogs/testCatalogWithEffectiveDateForExistingSubscriptionsCustomConfigNonMonthlyPlans/Insurance-v3.xml
- subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java
- util/src/main/java/org/killbill/billing/util/bcd/BillCycleDayCalculator.java
- util/src/test/java/org/killbill/billing/util/bcd/TestBillCycleDayCalculator.java
Fix review comments on https://github.com/killbill/killbill/pull/1877 and additional beatrix tests.
> Fix 1877 review comments

- jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PluginResource.java
Add missing headers from plugin response.
> jaxrs: Fix for issue #1901

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestInArrearChangeCancel.java
- beatrix/src/test/resources/catalogs/testInArrearChangeCancel/in_arrear.xml
- invoice/src/main/java/org/killbill/billing/invoice/generator/BillingIntervalDetail.java
- invoice/src/test/java/org/killbill/billing/invoice/model/TestRecurringInArrear.java
Added more tests and provided a fix for the issue described in #1907. Comments included in the code.
> Tests and fix proposal for #1907

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInvoicingIssue.java
- beatrix/src/test/resources/catalogs/testCatalogInArrearWithRecurringAndUsage/catalogTest.xml
> Test for invoice generation error

- catalog/pom.xml
- overdue/pom.xml
Pom file modifications to avoid release failure
> Pom file modifications

- pom.xml
Update oss-parent version for https://github.com/killbill/killbill-platform/issues/154
> Update oss-parent version

- catalog/pom.xml
- overdue/pom.xml
Same problem like [here](https://github.com/killbill/killbill-platform/pull/159).
> remove space as workaround fo maven release problem

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- beatrix/src/test/java/org/killbill/billing/beatrix/util/InvoiceChecker.java
- catalog/pom.xml
- invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java
- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- overdue/pom.xml
- Changes to invoke `onSuccessCall` for commit/void operations
- Added beatrix tests
> Fix for 1989

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogDailyBilling.java
- beatrix/src/test/resources/catalogs/testCatalogDailyBilling/catalog.xml
Based on the new tests using `DAILY` billing period, we can confirm that system works as expected.
>  Add tests for Daily billing period. See #2005

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.java
- invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceItemSqlDao.sql.stg
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceItemSqlDao.java
The original fix in 63ae35a90 was incomplete.
> invoice: Relax invoicing rules around additional items received from plugins. See #2004

- catalog/pom.xml
- invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceSqlDao.sql.stg
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java
- overdue/pom.xml
This PR addresses https://github.com/killbill/killbill/pull/1995#discussion_r1544847798. Out of  this, checks for `DRAFT`/`VOID`/migrated/written-off are implemented, parent balance is not yet implemented.
> Address review comments on 1995

- invoice/src/main/java/org/killbill/billing/invoice/api/user/DefaultInvoiceUserApi.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceModelDao.java
- invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java
- invoice/src/main/java/org/killbill/billing/invoice/model/SearchInvoice.java
- invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceSqlDao.sql.stg
- invoice/src/test/java/org/killbill/billing/invoice/api/user/TestDefaultInvoiceUserApi.java
- invoice/src/test/java/org/killbill/billing/invoice/dao/TestInvoiceDao.java
Added a `SearchInvoice` class as per https://github.com/killbill/killbill/pull/2021#discussion_r1627965080.
> Enhanced search return balance

- invoice/src/main/resources/org/killbill/billing/invoice/dao/InvoiceSqlDao.sql.stg
Changes as per https://github.com/killbill/killbill/pull/1995#discussion_r1622809487.
> Changes as per review comments

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationWithWrittenOffTag.java
- invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> Fix for 2000

- catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java
- catalog/src/test/java/org/killbill/billing/catalog/TestCatalogUpdater.java
Fix for Issue 3 in https://github.com/killbill/technical-support/issues/47. See https://github.com/killbill/technical-support/issues/47#issuecomment-2222049823.
> Fix for TS#47

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestAddonChangeAlignment.java
- beatrix/src/test/resources/catalogs/testAddonChangeAlignment/catalog-change-alignment.xml
Tests for change plan with `START_OF_BUNDLE` alignment
> 1739 tests

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestAddonChangeAlignment.java
- Includes minor corrections to `START_OF_BUNDLE` tests
- Includes new tests for `START_OF_SUBSCRPTION`
> Tests for change addon plan with START_OF_SUBSCRIPTION alignment

- usage/src/main/java/org/killbill/billing/usage/api/svcs/DefaultRawUsage.java
It is necessary as we sort these items during invoice generation.
> usage: Add missing equals() and hashCode() method to DefaultRawUsage

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTerm.java
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTermWithVersionedCatalogs.java
- beatrix/src/test/resources/catalogs/testCatalogFixedTermExpiry/WeaponsHireSmall.xml
- entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java
> Changes for #1930

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTermExpiry.java
New test for #1930, I missed checking in this test as part of https://github.com/killbill/killbill/pull/2046
> Test for #1930

- .github/workflows/ci.yml
- beatrix/src/test/java/org/killbill/billing/beatrix/integration/usage/TestUsageInvoicingIssue.java
- payment/src/main/java/org/killbill/billing/payment/core/sm/PluginControlPaymentAutomatonRunner.java
- payment/src/test/java/org/killbill/billing/payment/core/sm/TestRetryablePayment.java
Take a re-entrant lock to avoid the race condition.
> payment: fix for 1599

- entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java
Fix for https://github.com/killbill/killbill-aviate-plugin/issues/336
> Fix for aviate plugin 336

- catalog/src/main/java/org/killbill/billing/catalog/CatalogSafetyInitializer.java
I cannot think of any straightforward way to test this change with respect to the contention that we experienced. Luckily, the changes are fairly benign and take advantage of some Java 9+ features that did not exist when this class was written.
> Issue  #2116: Catalog initialization from plugin leads to lots of contention

- catalog/src/main/java/org/killbill/billing/catalog/CatalogSafetyInitializer.java
Replace synchronized statement on a per field level with a `ConcurrentHashMap` around the main `perCatalogClassNonRequiredFields` map.
> Fix for 2116

- invoice/src/main/java/org/killbill/billing/invoice/template/HtmlInvoiceGenerator.java
Work for https://github.com/killbill/killbill-aviate-plugin/issues/268 as per https://github.com/killbill/killbill-aviate-plugin/pull/439#issuecomment-2971727663
> Work for aviate 268

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- account/pom.xml
- api/pom.xml
- beatrix/pom.xml
- catalog/pom.xml
- currency/pom.xml
- entitlement/pom.xml
- invoice/pom.xml
- jaxrs/pom.xml
- junction/pom.xml
- overdue/pom.xml
- payment/pom.xml
- pom.xml
- profiles/killbill/pom.xml
- profiles/killpay/pom.xml
- profiles/pom.xml
- subscription/pom.xml
- tenant/pom.xml
- usage/pom.xml
- util/pom.xml
Changes for ossrh migration. Released KB 0.24.15 with these changes.
> Fix release

- beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTermExpiry.java
- junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BlockingCalculator.java
The previous code would compute blocked duration using the subscription#endDate as a filter, but for expired subscription, subscription#endDate is null so we need to extract the date from the billing event.
> junction: Fix NPE for expired + resumed subscriptions. See #2150
